/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/connections": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Connections
     * @description The company's ATS connections; every member sees them, only owners and admins change
     *     them.
     */
    get: operations["list_connections_connections_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/workable": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * Connect Workable
     * @description Connects Workable with an account's API access token, checked with one read first. A
     *     second connect replaces the key.
     */
    put: operations["connect_workable_workable_put"]
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/greenhouse": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * Connect Greenhouse
     * @description Connects Greenhouse with a Harvest V3 (OAuth) API credential, checked with one read
     *     first. Each connection gets its own secret key for the web hook the company sets up; a
     *     reconnect keeps it, so the web hook goes on working.
     */
    put: operations["connect_greenhouse_greenhouse_put"]
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/greenhouse/webhook": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Greenhouse Webhook
     * @description Where the company's Greenhouse web hook sends stage changes, and its secret key, to paste
     *     into Greenhouse; owners and admins only.
     */
    get: operations["greenhouse_webhook_greenhouse_webhook_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/{provider}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Disconnect
     * @description Disconnects: Workable's notifications are cancelled, then the key is deleted, and its
     *     linked jobs with it.
     */
    delete: operations["disconnect__provider__delete"]
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/{provider}/jobs": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Jobs */
    get: operations["list_jobs__provider__jobs_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/{provider}/jobs/{job_id}/stages": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Stages */
    get: operations["list_stages__provider__jobs__job_id__stages_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/{provider}/jobs/{job_id}/text": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Job Text Of
     * @description A job's title, description, requirements and benefits as plain text, to make an
     *     interview from (the same limit as a pasted job description).
     */
    get: operations["job_text_of__provider__jobs__job_id__text_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/links": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Links */
    get: operations["list_links_links_get"]
    put?: never
    /**
     * Add Link
     * @description Links an ATS job to one of the company's interviews: its candidates who reach the stage
     *     will get the interview. A job has one interview.
     */
    post: operations["add_link_links_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/links/{link_id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Remove Link */
    delete: operations["remove_link_links__link_id__delete"]
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/links/{link_id}/retry": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Retry Candidates
     * @description Invites again the candidates the ATS sent for this job who weren't invited (after a
     *     top-up, or once the pause is off).
     */
    post: operations["retry_candidates_links__link_id__retry_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/webhooks/workable/{link_id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Workable Event
     * @description Workable's events for one linked job, signed with the account's token (checked on the raw
     *     body). Open in maintenance mode like every /webhooks/ route, so no candidate is lost.
     */
    post: operations["workable_event_webhooks_workable__link_id__post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/webhooks/greenhouse/{connection_id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Greenhouse Event
     * @description The company's Greenhouse web hook (stage changes), signed with the connection's secret key
     *     (the Signature header, checked on the raw body). Greenhouse's ping on saving it is
     *     answered too.
     */
    post: operations["greenhouse_event_webhooks_greenhouse__connection_id__post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/events": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Receive Event
     * @description Pub/Sub pushes every event here. A failure answers with an error, so Pub/Sub retries it,
     *     and moves it to the dead-letter topic after the subscription's maximum attempts.
     */
    post: operations["receive_event_internal_events_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/schedules/outbox": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Flush Outbox
     * @description Every minute, from Cloud Scheduler: publishes events that weren't published right after
     *     their change.
     */
    post: operations["flush_outbox_internal_schedules_outbox_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/schedules/recover": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Recover
     * @description Daily, from Cloud Scheduler: invites cut off midway start again (companies refuses them
     *     during the emergency pause, and they're kept to retry), and candidates past their
     *     retention period go.
     */
    post: operations["recover_internal_schedules_recover_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/users/{user_id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Delete User
     * @description Library, deleting an account: an ATS's records of them as a candidate go.
     */
    delete: operations["delete_user_internal_users__user_id__delete"]
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/users/{user_id}/export": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Export User
     * @description Library, for "Download my data": what ATSs sent about them as a candidate.
     */
    get: operations["export_user_internal_users__user_id__export_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/health": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Health */
    get: operations["health_health_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/ready": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Ready
     * @description Ready once the database answers; Docker's healthcheck and the startup probe use this. Redis
     *     isn't checked: an outage there shouldn't stop the service from starting.
     */
    get: operations["ready_ready_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * AtsItemOut
     * @description A job or a stage in the ATS: its own id and name.
     */
    AtsItemOut: {
      /** Id */
      id: string
      /** Name */
      name: string
    }
    /**
     * AtsProvider
     * @description The applicant tracking systems a company can connect.
     * @enum {string}
     */
    AtsProvider: "workable" | "greenhouse"
    /**
     * ConnectionOut
     * @description A connection as the company sees it: never its key.
     */
    ConnectionOut: {
      provider: components["schemas"]["AtsProvider"]
      /** Account */
      account: string
      status: components["schemas"]["ConnectionStatus"]
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
    }
    /**
     * ConnectionStatus
     * @enum {string}
     */
    ConnectionStatus: "connected" | "broken"
    /** GreenhouseIn */
    GreenhouseIn: {
      /** Client Id */
      client_id: string
      /** Client Secret */
      client_secret: string
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][]
    }
    /** IntegrationsOut */
    IntegrationsOut: {
      /** Available */
      available: boolean
      /** Connections */
      connections: components["schemas"]["ConnectionOut"][]
    }
    /** JobLinkIn */
    JobLinkIn: {
      provider: components["schemas"]["AtsProvider"]
      /** Job Id */
      job_id: string
      /** Stage Id */
      stage_id: string
      /**
       * Interview Id
       * Format: uuid
       */
      interview_id: string
    }
    /** JobLinkOut */
    JobLinkOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      provider: components["schemas"]["AtsProvider"]
      /** Job Name */
      job_name: string
      /** Stage Name */
      stage_name: string
      /**
       * Interview Id
       * Format: uuid
       */
      interview_id: string
      /** Interview Title */
      interview_title: string | null
      /**
       * Invited
       * @default 0
       */
      invited: number
      /**
       * Not Invited
       * @default 0
       */
      not_invited: number
      /**
       * Waiting
       * @default 0
       */
      waiting: number
    }
    /**
     * JobTextOut
     * @description A job's text to make an interview from, which the company can edit first.
     */
    JobTextOut: {
      /** Text */
      text: string
    }
    /**
     * PushBody
     * @description What Pub/Sub sends to a push endpoint.
     */
    PushBody: {
      message: components["schemas"]["PushMessage"]
      /** Subscription */
      subscription: string
    }
    /** PushMessage */
    PushMessage: {
      /**
       * Data
       * @default
       */
      data: string
      /**
       * Attributes
       * @default {}
       */
      attributes: {
        [key: string]: string
      }
      /** Messageid */
      messageId: string
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
      /** Input */
      input?: unknown
      /** Context */
      ctx?: Record<string, never>
    }
    /**
     * WebhookOut
     * @description What the company pastes into its ATS's web hook: where it sends, and its secret key.
     */
    WebhookOut: {
      /** Url */
      url: string
      /** Secret */
      secret: string
    }
    /** WorkableIn */
    WorkableIn: {
      /** Account */
      account: string
      /** Token */
      token: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  list_connections_connections_get: {
    parameters: {
      query: {
        company_id: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["IntegrationsOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  connect_workable_workable_put: {
    parameters: {
      query: {
        company_id: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["WorkableIn"]
      }
    }
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  connect_greenhouse_greenhouse_put: {
    parameters: {
      query: {
        company_id: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["GreenhouseIn"]
      }
    }
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  greenhouse_webhook_greenhouse_webhook_get: {
    parameters: {
      query: {
        company_id: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["WebhookOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  disconnect__provider__delete: {
    parameters: {
      query: {
        company_id: string
      }
      header?: never
      path: {
        provider: components["schemas"]["AtsProvider"]
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  list_jobs__provider__jobs_get: {
    parameters: {
      query: {
        company_id: string
      }
      header?: never
      path: {
        provider: components["schemas"]["AtsProvider"]
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["AtsItemOut"][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  list_stages__provider__jobs__job_id__stages_get: {
    parameters: {
      query: {
        company_id: string
      }
      header?: never
      path: {
        provider: components["schemas"]["AtsProvider"]
        job_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["AtsItemOut"][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  job_text_of__provider__jobs__job_id__text_get: {
    parameters: {
      query: {
        company_id: string
      }
      header?: never
      path: {
        provider: components["schemas"]["AtsProvider"]
        job_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["JobTextOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  list_links_links_get: {
    parameters: {
      query: {
        company_id: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["JobLinkOut"][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  add_link_links_post: {
    parameters: {
      query: {
        company_id: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["JobLinkIn"]
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  remove_link_links__link_id__delete: {
    parameters: {
      query: {
        company_id: string
      }
      header?: never
      path: {
        link_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  retry_candidates_links__link_id__retry_post: {
    parameters: {
      query: {
        company_id: string
      }
      header?: never
      path: {
        link_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  workable_event_webhooks_workable__link_id__post: {
    parameters: {
      query?: never
      header?: never
      path: {
        link_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  greenhouse_event_webhooks_greenhouse__connection_id__post: {
    parameters: {
      query?: never
      header?: never
      path: {
        connection_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  receive_event_internal_events_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["PushBody"]
      }
    }
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  flush_outbox_internal_schedules_outbox_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  recover_internal_schedules_recover_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  delete_user_internal_users__user_id__delete: {
    parameters: {
      query: {
        email: string
      }
      header?: never
      path: {
        user_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  export_user_internal_users__user_id__export_get: {
    parameters: {
      query: {
        email: string
      }
      header?: never
      path: {
        user_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            [key: string]: unknown
          }
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  health_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            [key: string]: unknown
          }
        }
      }
    }
  }
  ready_ready_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            [key: string]: unknown
          }
        }
      }
    }
  }
}
