/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/catalog": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Catalog */
    get: operations["catalog_catalog_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/webhooks/paddle": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Paddle Webhook
     * @description Paddle retries until it gets a 2xx, and granting is idempotent, so retries are safe.
     */
    post: operations["paddle_webhook_webhooks_paddle_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/candidates/hold": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Hold Candidate
     * @description Set aside on invite. Charged once the interview finishes with at least one answer.
     */
    post: operations["hold_candidate_internal_candidates_hold_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/candidates/charge": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Charge Candidate */
    post: operations["charge_candidate_internal_candidates_charge_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/candidates/release": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Release Candidate */
    post: operations["release_candidate_internal_candidates_release_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/companies/{company_id}/welcome": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Welcome Company
     * @description The company's wallet. The welcome credits come once per owner's email; a company new
     *     in that sense can be referred by another, unrelated one.
     */
    post: operations["welcome_company_internal_companies__company_id__welcome_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/companies/{company_id}/referral": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Company Referral */
    get: operations["company_referral_internal_companies__company_id__referral_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/companies/{company_id}/credits": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Company Credits */
    get: operations["company_credits_internal_companies__company_id__credits_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/companies/credits": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Companies Credits
     * @description Several companies' balances at once, for the top-up page.
     */
    post: operations["companies_credits_internal_companies_credits_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/companies/{company_id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Delete Company */
    delete: operations["delete_company_internal_companies__company_id__delete"]
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/users/{user_id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Delete User
     * @description The user's purchases for their companies stay for bookkeeping, without their id; any
     *     automatic top-up paid with their card goes off.
     */
    delete: operations["delete_user_internal_users__user_id__delete"]
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/users/{user_id}/export": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Export User
     * @description What the user bought for their companies.
     */
    get: operations["export_user_internal_users__user_id__export_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/companies/{company_id}/auto-top-up": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Company Auto Top Up */
    get: operations["company_auto_top_up_internal_companies__company_id__auto_top_up_get"]
    /** Turn On Company */
    put: operations["turn_on_company_internal_companies__company_id__auto_top_up_put"]
    post?: never
    /** Turn Off Company */
    delete: operations["turn_off_company_internal_companies__company_id__auto_top_up_delete"]
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/health": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Health */
    get: operations["health_health_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/ready": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Ready
     * @description Ready only once the database answers; Docker's healthcheck uses this.
     */
    get: operations["ready_ready_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * AutoTopUpIn
     * @description Which top-up to buy, and under which available balance (credits).
     */
    AutoTopUpIn: {
      /** Product */
      product: string
      /** Threshold */
      threshold: number
    }
    /**
     * AutoTopUpOut
     * @description A wallet's automatic top-up: whether it's offered at all, running, or waiting for its
     *     checkout, what it buys and when, and the choices.
     */
    AutoTopUpOut: {
      /** Offered */
      offered: boolean
      /** On */
      on: boolean
      /** Waiting */
      waiting: boolean
      /** Product */
      product: string | null
      /** Threshold */
      threshold: number | null
      /** Products */
      products: string[]
      /** Thresholds */
      thresholds: number[]
      checkout?: components["schemas"]["CheckoutOut"] | null
    }
    /** BalanceOut */
    BalanceOut: {
      /** Balance */
      balance: number
      /** Reserved */
      reserved: number
      /** Available */
      available: number
      /** Low */
      low: boolean
    }
    /**
     * CandidatePriceOut
     * @description A candidate's price when credits are bought in a top-up from this many dollars.
     */
    CandidatePriceOut: {
      /** From Dollars */
      from_dollars: number
      /** Cents */
      cents: number
    }
    /**
     * CatalogOut
     * @description What the pricing page and Paddle.js need. Prices are decided here, not in the client.
     */
    CatalogOut: {
      /** Environment */
      environment: string
      /** Client Token */
      client_token: string
      /** Currency */
      currency: string
      /** Candidate Credits */
      candidate_credits: number
      /** Candidate Prices */
      candidate_prices: components["schemas"]["CandidatePriceOut"][]
      /** Welcome Company */
      welcome_company: number
      /** Referral Company */
      referral_company: number
      /** Products */
      products: components["schemas"]["TopUpOut"][]
    }
    /**
     * CheckoutOut
     * @description The Paddle checkout to open: its price and the custom data to send with it.
     */
    CheckoutOut: {
      /** Price Id */
      price_id: string
      /** Custom Data */
      custom_data: {
        [key: string]: string
      }
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][]
    }
    /** OwnersIn */
    OwnersIn: {
      /** Owner Ids */
      owner_ids: string[]
    }
    /**
     * ReferralOut
     * @description The owner's referral link code, what it earns, and how many it has earned for.
     */
    ReferralOut: {
      /** Code */
      code: string
      /** Reward */
      reward: number
      /** Rewarded */
      rewarded: number
      /** Rewards */
      rewards: components["schemas"]["ReferralRewardOut"][]
    }
    /**
     * ReferralRewardOut
     * @description A company that came through the link and topped up, so both got the reward.
     */
    ReferralRewardOut: {
      /** Company Id */
      company_id: string
      /**
       * Rewarded At
       * Format: date-time
       */
      rewarded_at: string
    }
    /** TopUpOut */
    TopUpOut: {
      /** Key */
      key: string
      /** Title */
      title: string
      /** Price Cents */
      price_cents: number
      /** Credits */
      credits: number
      /** Candidates */
      candidates: number
      /** Candidate Cents */
      candidate_cents: number
      /** Price Id */
      price_id: string | null
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
      /** Input */
      input?: unknown
      /** Context */
      ctx?: Record<string, never>
    }
    /** WelcomeIn */
    WelcomeIn: {
      /** Owner Email */
      owner_email: string
      /** Referral */
      referral?: string | null
      /**
       * Related
       * @default []
       */
      related: string[]
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  catalog_catalog_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["CatalogOut"]
        }
      }
    }
  }
  paddle_webhook_webhooks_paddle_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            [key: string]: unknown
          }
        }
      }
    }
  }
  hold_candidate_internal_candidates_hold_post: {
    parameters: {
      query: {
        company_id: string
        key: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  charge_candidate_internal_candidates_charge_post: {
    parameters: {
      query: {
        key: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  release_candidate_internal_candidates_release_post: {
    parameters: {
      query: {
        key: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  welcome_company_internal_companies__company_id__welcome_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        company_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["WelcomeIn"]
      }
    }
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  company_referral_internal_companies__company_id__referral_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        company_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ReferralOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  company_credits_internal_companies__company_id__credits_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        company_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["BalanceOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  companies_credits_internal_companies_credits_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["OwnersIn"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            [key: string]: components["schemas"]["BalanceOut"]
          }
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  delete_company_internal_companies__company_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        company_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  delete_user_internal_users__user_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        user_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  export_user_internal_users__user_id__export_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        user_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            [key: string]: unknown
          }
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  company_auto_top_up_internal_companies__company_id__auto_top_up_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        company_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["AutoTopUpOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  turn_on_company_internal_companies__company_id__auto_top_up_put: {
    parameters: {
      query: {
        buyer_id: string
      }
      header?: never
      path: {
        company_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["AutoTopUpIn"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["AutoTopUpOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  turn_off_company_internal_companies__company_id__auto_top_up_delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        company_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  health_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            [key: string]: unknown
          }
        }
      }
    }
  }
  ready_ready_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            [key: string]: unknown
          }
        }
      }
    }
  }
}
