/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/companies": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Companies */
    get: operations["list_companies_companies_get"]
    put?: never
    /** Create Company */
    post: operations["create_company_companies_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/companies/credits": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Credits
     * @description The user's companies with their credits; any member may top one up. Declared before
     *     /{company_id}, which would otherwise take "credits" as an id.
     */
    get: operations["list_credits_companies_credits_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/companies/{company_id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Company */
    get: operations["get_company_companies__company_id__get"]
    put?: never
    post?: never
    /**
     * Delete Company
     * @description Only the owner can do it.
     */
    delete: operations["delete_company_companies__company_id__delete"]
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/companies/{company_id}/credits": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Credits
     * @description Candidates the company can still invite; any member may see it.
     */
    get: operations["get_credits_companies__company_id__credits_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/companies/{company_id}/referral": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Referral
     * @description The company's referral link; any member may share it.
     */
    get: operations["get_referral_companies__company_id__referral_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/companies/{company_id}/name": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /**
     * Rename Company
     * @description Owners and admins rename the company; names stay unique across prepza, ignoring case.
     */
    patch: operations["rename_company_companies__company_id__name_patch"]
    trace?: never
  }
  "/companies/{company_id}/auto-top-up": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Auto Top Up */
    get: operations["get_auto_top_up_companies__company_id__auto_top_up_get"]
    /** Turn On */
    put: operations["turn_on_companies__company_id__auto_top_up_put"]
    post?: never
    /** Turn Off */
    delete: operations["turn_off_companies__company_id__auto_top_up_delete"]
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/members": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Members */
    get: operations["list_members_members_get"]
    put?: never
    /** Invite Admin */
    post: operations["invite_admin_members_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/members/invites/{token}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Admin Invite */
    get: operations["get_admin_invite_members_invites__token__get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/members/invites/{token}/accept": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Accept Admin Invite
     * @description Only the invited email can accept, so a forwarded link is useless to anyone else.
     */
    post: operations["accept_admin_invite_members_invites__token__accept_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/interviews": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Interviews */
    get: operations["list_interviews_interviews_get"]
    put?: never
    /** Create Interview */
    post: operations["create_interview_interviews_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/interviews/from-template": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Create From Template
     * @description A test copied from a template: free and ready at once, so no generation limits apply.
     */
    post: operations["create_from_template_interviews_from_template_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/interviews/{interview_id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Interview */
    get: operations["get_interview_interviews__interview_id__get"]
    put?: never
    post?: never
    /**
     * Delete Interview
     * @description Results and questions go first, so a failure leaves the interview to delete again.
     */
    delete: operations["delete_interview_interviews__interview_id__delete"]
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/interviews/{interview_id}/settings": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Update Settings */
    patch: operations["update_settings_interviews__interview_id__settings_patch"]
    trace?: never
  }
  "/interviews/{interview_id}/title": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /**
     * Rename Interview
     * @description Company owners and admins can rename an interview once it has been generated.
     */
    patch: operations["rename_interview_interviews__interview_id__title_patch"]
    trace?: never
  }
  "/interviews/{interview_id}/preview": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Preview Interview
     * @description A company member takes their own test as a candidate would: free, kept out of the
     *     candidate list, and its answers out of the questions' statistics. Each preview is new.
     */
    post: operations["preview_interview_interviews__interview_id__preview_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/interviews/{interview_id}/candidates": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Candidates
     * @description A page at a time, best grade first or newest first, narrowed to an email containing `q`
     *     and a status or result. Results come from rounds: for every candidate when sorting or
     *     filtering by them, otherwise for this page only.
     */
    get: operations["list_candidates_interviews__interview_id__candidates_get"]
    put?: never
    /** Invite Candidate */
    post: operations["invite_candidate_interviews__interview_id__candidates_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/interviews/candidates/filters": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Candidate Filters
     * @description What candidates can be filtered by.
     */
    get: operations["candidate_filters_interviews_candidates_filters_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/interviews/{interview_id}/candidates/{invite_id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Candidate Scorecard */
    get: operations["candidate_scorecard_interviews__interview_id__candidates__invite_id__get"]
    put?: never
    post?: never
    /**
     * Revoke Candidate
     * @description Withdraws an invite the candidate hasn't used yet; later it would discard their answers.
     */
    delete: operations["revoke_candidate_interviews__interview_id__candidates__invite_id__delete"]
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/interviews/{interview_id}/candidates/{invite_id}/extra-time": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /** Set Extra Time */
    put: operations["set_extra_time_interviews__interview_id__candidates__invite_id__extra_time_put"]
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/interviews/{interview_id}/candidates/bulk": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Invite Many
     * @description Invites every email in a pasted or uploaded list, one by one as a single invite would,
     *     and says who was invited and why the others weren't.
     */
    post: operations["invite_many_interviews__interview_id__candidates_bulk_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/interviews/{interview_id}/generation": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Generation
     * @description Every company member follows the generation, not only the admin who started it.
     */
    get: operations["get_generation_interviews__interview_id__generation_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/interviews/{interview_id}/generation/review": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Review Generation */
    post: operations["review_generation_interviews__interview_id__generation_review_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/interviews/{interview_id}/generation/retry": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Retry Generation */
    post: operations["retry_generation_interviews__interview_id__generation_retry_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/interviews/{interview_id}/generation/cancel": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Cancel Generation
     * @description Removes the interview too, so it isn't left without questions.
     */
    post: operations["cancel_generation_interviews__interview_id__generation_cancel_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/interviews/{interview_id}/topics/{topic_id}/questions": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Topic Questions */
    get: operations["list_topic_questions_interviews__interview_id__topics__topic_id__questions_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/interviews/{interview_id}/topics/{topic_id}/limit": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /** Set Topic Limit */
    put: operations["set_topic_limit_interviews__interview_id__topics__topic_id__limit_put"]
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/interviews/{interview_id}/questions/{question_id}/regenerate": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Regenerate Question */
    post: operations["regenerate_question_interviews__interview_id__questions__question_id__regenerate_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/interviews/{interview_id}/questions/{question_id}/wrong": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Mark Wrong
     * @description One click: the marked answer is wrong. The verifier checks it and fixes or replaces it.
     */
    post: operations["mark_wrong_interviews__interview_id__questions__question_id__wrong_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/interviews/{interview_id}/questions/{question_id}/reports": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Question Reports */
    get: operations["list_question_reports_interviews__interview_id__questions__question_id__reports_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/invites/{token}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Invite */
    get: operations["get_invite_invites__token__get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/invites/{token}/start": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Start Invite
     * @description Only the invited, verified email can start; a forwarded link is useless to anyone else.
     */
    post: operations["start_invite_invites__token__start_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/interviews/{interview_id}/link": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * Set Link
     * @description Owners and admins turn the link on (a new code) or off (it stops working at once).
     */
    put: operations["set_link_interviews__interview_id__link_put"]
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/links/{token}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Link
     * @description Shown to anyone with the link, signed in or not, before they start. Signed in, it also
     *     says how far they got, so a finished test is never offered again.
     */
    get: operations["get_link_links__token__get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/links/{token}/start": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Start Link
     * @description The signed-in person becomes a candidate (their verified email, one attempt each) and
     *     starts, with credits set aside as for an email invite.
     */
    post: operations["start_link_links__token__start_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/companies/{company_id}/logo": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Logo
     * @description Public: candidates' pages and email clients load it without signing in.
     */
    get: operations["get_logo_companies__company_id__logo_get"]
    /**
     * Set Logo
     * @description Any of the company's owners and admins sets the logo: PNG, JPEG or WebP, up to 500 KB.
     */
    put: operations["set_logo_companies__company_id__logo_put"]
    post?: never
    /** Remove Logo */
    delete: operations["remove_logo_companies__company_id__logo_delete"]
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/candidates/{invite_id}/brand": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Candidate Brand
     * @description The company and logo for the candidate taking the interview, or a member previewing it.
     */
    get: operations["candidate_brand_candidates__invite_id__brand_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/interviews/{interview_id}/candidates/{invite_id}/report/email": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Email Report
     * @description Emails the candidate's PDF report, made on their page, to someone such as a hiring
     *     manager. A reply goes to the member who sent it. Counts towards the member's email limits.
     */
    post: operations["email_report_interviews__interview_id__candidates__invite_id__report_email_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/interviews/{interview_id}/report": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Interview Report */
    get: operations["interview_report_interviews__interview_id__report_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/interviews/{interview_id}/report/email": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Email Interview Report
     * @description Emails the test's candidates report, made on its candidates tab, like a candidate's.
     */
    post: operations["email_interview_report_interviews__interview_id__report_email_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/interviews/{interview_id}/suggestions": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Suggested Talents */
    get: operations["suggested_talents_interviews__interview_id__suggestions_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/interviews/{interview_id}/suggestions/hide": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Hide Talent
     * @description Hides a talent who doesn't fit from this test's suggestions, for everyone in the company.
     */
    post: operations["hide_talent_interviews__interview_id__suggestions_hide_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/companies/{company_id}/website": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /** Set Website */
    put: operations["set_website_companies__company_id__website_put"]
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/users/{user_id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Delete User
     * @description Part of deleting an account (library coordinates it); safe to repeat.
     */
    delete: operations["delete_user_internal_users__user_id__delete"]
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/users/{user_id}/export": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Export User */
    get: operations["export_user_internal_users__user_id__export_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/users/{user_id}/companies": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * User Companies
     * @description Every company the user is a member of, in any role; notifications sends them theirs.
     */
    get: operations["user_companies_internal_users__user_id__companies_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/invites/{invite_id}/undelivered": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Invite Undelivered
     * @description Notifications reports a bounced or spam-flagged invite email; safe to repeat. The
     *     company is told.
     */
    post: operations["invite_undelivered_internal_invites__invite_id__undelivered_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/events": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Receive Event
     * @description Pub/Sub pushes every event here. A failure answers with an error, so Pub/Sub retries it,
     *     and moves it to the dead-letter topic after the subscription's maximum attempts.
     */
    post: operations["receive_event_internal_events_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/schedules/retention": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Retention
     * @description Daily, from Cloud Scheduler: candidate data past its retention period goes.
     */
    post: operations["retention_internal_schedules_retention_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/schedules/invite-expiry": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Invite Expiry
     * @description Daily, from Cloud Scheduler: invites never started expire, and their credits come back.
     */
    post: operations["invite_expiry_internal_schedules_invite_expiry_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/schedules/invite-reminders": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Invite Reminders
     * @description Daily, from Cloud Scheduler: candidates who haven't started get one reminder.
     */
    post: operations["invite_reminders_internal_schedules_invite_reminders_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/schedules/outbox": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Flush Outbox
     * @description Every minute, from Cloud Scheduler: publishes events that weren't published right after
     *     their change.
     */
    post: operations["flush_outbox_internal_schedules_outbox_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/health": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Health */
    get: operations["health_health_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/ready": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Ready
     * @description Ready only once the database and Redis answer; Docker's healthcheck uses this.
     */
    get: operations["ready_ready_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * AdminInviteOut
     * @description What the invited admin sees before accepting.
     */
    AdminInviteOut: {
      /** Company Name */
      company_name: string
      /** Email */
      email: string
      /** Joined */
      joined: boolean
    }
    /**
     * AutoTopUpIn
     * @description Which top-up to buy, and under which available balance (credits).
     */
    AutoTopUpIn: {
      /** Product */
      product: string
      /** Threshold */
      threshold: number
    }
    /**
     * AutoTopUpOut
     * @description The company's automatic top-up, as billing has it.
     */
    AutoTopUpOut: {
      /** Offered */
      offered: boolean
      /** On */
      on: boolean
      /** Waiting */
      waiting: boolean
      /** Product */
      product: string | null
      /** Threshold */
      threshold: number | null
      /** Products */
      products: string[]
      /** Thresholds */
      thresholds: number[]
      checkout?: components["schemas"]["CheckoutOut"] | null
    }
    /**
     * BrandOut
     * @description Who a candidate's interview is for, shown while they take it.
     */
    BrandOut: {
      /** Company */
      company: string
      /** Logo Url */
      logo_url: string | null
    }
    /**
     * BulkInviteIn
     * @description A list of emails as pasted or read from a file; any other text around them is ignored.
     */
    BulkInviteIn: {
      /** Text */
      text: string
    }
    /** BulkInviteOut */
    BulkInviteOut: {
      /** Invited */
      invited: string[]
      /** Skipped */
      skipped: components["schemas"]["SkippedInvite"][]
    }
    /**
     * CandidateFilter
     * @enum {string}
     */
    CandidateFilter:
      | "invited"
      | "in_process"
      | "finished"
      | "passed"
      | "flagged"
      | "undelivered"
      | "expired"
    /**
     * CandidateFiltersOut
     * @description What a company can narrow its candidates to: statuses and results.
     */
    CandidateFiltersOut: {
      /** Filters */
      filters: string[]
    }
    /** CandidateIn */
    CandidateIn: {
      /**
       * Email
       * Format: email
       */
      email: string
    }
    /** CandidateOut */
    CandidateOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Email */
      email: string
      /** Status */
      status: string
      /**
       * Progress
       * @default 0
       */
      progress: number
      /** Grade */
      grade?: number | null
      /** Passed */
      passed?: boolean | null
      /**
       * Tab Leaves
       * @default 0
       */
      tab_leaves: number
      /**
       * Copies
       * @default 0
       */
      copies: number
      /**
       * Fast Answers
       * @default 0
       */
      fast_answers: number
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
    }
    /**
     * CandidateSort
     * @enum {string}
     */
    CandidateSort: "grade" | "date"
    /**
     * CheckoutOut
     * @description The Paddle checkout to open: its price and the custom data to send with it.
     */
    CheckoutOut: {
      /** Price Id */
      price_id: string
      /** Custom Data */
      custom_data: {
        [key: string]: string
      }
    }
    /**
     * CompanyBalanceOut
     * @description A company the user can top up, with its credits.
     */
    CompanyBalanceOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Name */
      name: string
      /** Available */
      available: number
      /** Low */
      low: boolean
    }
    /** CompanyCreate */
    CompanyCreate: {
      /** Name */
      name: string
    }
    /** CompanyCreditsOut */
    CompanyCreditsOut: {
      /** Available */
      available: number
      /** Low */
      low: boolean
    }
    /** CompanyOut */
    CompanyOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Name */
      name: string
      /** Role */
      role: string
      /** Interview Count */
      interview_count: number
      /** Logo Url */
      logo_url?: string | null
      /** Website Domain */
      website_domain?: string | null
      /** Verified Domain */
      verified_domain?: string | null
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
    }
    /**
     * CompanyRename
     * @description A new name, edited in place like a test's title (hence `title`).
     */
    CompanyRename: {
      /** Title */
      title: string
    }
    /**
     * ExtraTimeIn
     * @description Extra time for a candidate who needs it, in percent of each question's time.
     */
    ExtraTimeIn: {
      /** Extra Time */
      extra_time: number
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][]
    }
    /** HideTalentIn */
    HideTalentIn: {
      /** Url */
      url: string
    }
    /** InterviewCreate */
    InterviewCreate: {
      /** Text */
      text: string
      /** Generate In */
      generate_in?:
        | (
            | "en"
            | "ru"
            | "uk"
            | "es"
            | "pt"
            | "de"
            | "fr"
            | "it"
            | "pl"
            | "nl"
            | "tr"
            | "ar"
            | "he"
            | "fa"
            | "ja"
            | "zh"
            | "ko"
            | "hi"
            | "id"
            | "th"
            | "vi"
            | "fil"
            | "et"
          )
        | null
    }
    /** InterviewDetail */
    InterviewDetail: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Generation Id */
      generation_id: string | null
      /** Set Id */
      set_id: string | null
      /** Title */
      title: string | null
      /** Question Seconds */
      question_seconds: number
      /** Candidate Count */
      candidate_count: number
      /** Hired */
      hired: boolean
      /** Pass Mark */
      pass_mark: number
      /** Link Token */
      link_token: string | null
      /** Status */
      status: string
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Topics */
      topics: components["schemas"]["TopicOut"][]
    }
    /** InterviewFromTemplate */
    InterviewFromTemplate: {
      /**
       * Template Id
       * Format: uuid
       */
      template_id: string
    }
    /** InterviewOut */
    InterviewOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Generation Id */
      generation_id: string | null
      /** Set Id */
      set_id: string | null
      /** Title */
      title: string | null
      /** Question Seconds */
      question_seconds: number
      /** Candidate Count */
      candidate_count: number
      /** Hired */
      hired: boolean
      /** Pass Mark */
      pass_mark: number
      /** Link Token */
      link_token: string | null
      /** Status */
      status: string
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
    }
    /**
     * InterviewReportOut
     * @description Every candidate of a test with their totals, as its candidates tab lists them, for the
     *     test's PDF report: best grade first.
     */
    InterviewReportOut: {
      /** Title */
      title: string | null
      /** Company */
      company: string
      /** Logo Url */
      logo_url: string | null
      /** Verified Domain */
      verified_domain: string | null
      /** Pass Mark */
      pass_mark: number
      /** Candidates */
      candidates: components["schemas"]["CandidateOut"][]
    }
    /** InterviewSettings */
    InterviewSettings: {
      /**
       * Question Seconds
       * @default 60
       */
      question_seconds: number
      /**
       * Hired
       * @default false
       */
      hired: boolean
      /**
       * Pass Mark
       * @default 70
       */
      pass_mark: number
    }
    /** InviteStartOut */
    InviteStartOut: {
      /** Sessions */
      sessions: components["schemas"]["SessionSummary"][]
    }
    /** InviteView */
    InviteView: {
      /**
       * Interview Id
       * Format: uuid
       */
      interview_id: string
      /** Title */
      title: string | null
      /** Company */
      company: string
      /** Logo Url */
      logo_url?: string | null
      /** Verified Domain */
      verified_domain?: string | null
      /** Email */
      email: string
      /** Status */
      status: string
      /** Question Seconds */
      question_seconds: number
    }
    /** LinkIn */
    LinkIn: {
      /** On */
      on: boolean
    }
    /**
     * LinkOut
     * @description The test's shareable link code, or None while it's off.
     */
    LinkOut: {
      /** Link Token */
      link_token: string | null
    }
    /**
     * LinkView
     * @description What a test's shareable link shows before anyone starts.
     */
    LinkView: {
      /** Title */
      title: string | null
      /** Company */
      company: string
      /** Logo Url */
      logo_url?: string | null
      /** Verified Domain */
      verified_domain?: string | null
      /** Question Seconds */
      question_seconds: number
      /** Status */
      status?: string | null
    }
    /**
     * LogoIn
     * @description The logo image, base64-encoded.
     */
    LogoIn: {
      /** Image */
      image: string
    }
    /** LogoOut */
    LogoOut: {
      /** Logo Url */
      logo_url: string | null
    }
    /** MemberIn */
    MemberIn: {
      /**
       * Email
       * Format: email
       */
      email: string
    }
    /** MemberOut */
    MemberOut: {
      /** Email */
      email: string
      /** Role */
      role: string
      /** Joined */
      joined: boolean
      /** Token */
      token?: string | null
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
    }
    /**
     * PreviewOut
     * @description The first session of a member's preview, to open in the player.
     */
    PreviewOut: {
      /**
       * Session Id
       * Format: uuid
       */
      session_id: string
    }
    /**
     * PushBody
     * @description What Pub/Sub sends to a push endpoint.
     */
    PushBody: {
      message: components["schemas"]["PushMessage"]
      /** Subscription */
      subscription: string
    }
    /** PushMessage */
    PushMessage: {
      /**
       * Data
       * @default
       */
      data: string
      /**
       * Attributes
       * @default {}
       */
      attributes: {
        [key: string]: string
      }
      /** Messageid */
      messageId: string
    }
    /** QuestionOption */
    QuestionOption: {
      /** Answer */
      answer: string
      /** Correct */
      correct: boolean
    }
    /**
     * QuestionText
     * @description A question as the company manages it: text, answer options and feedback counts.
     */
    QuestionText: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Text */
      text: string
      /** Options */
      options: components["schemas"]["QuestionOption"][]
      /** Likes */
      likes: number
      /** Dislikes */
      dislikes: number
      /** Reports */
      reports: number
    }
    /**
     * ReferralOut
     * @description The company's referral link code, what it earns, how many it has earned for, and the latest
     *     of those, newest first.
     */
    ReferralOut: {
      /** Code */
      code: string
      /** Reward */
      reward: number
      /** Rewarded */
      rewarded: number
      /** Rewards */
      rewards: components["schemas"]["ReferralRewardOut"][]
    }
    /**
     * ReferralRewardOut
     * @description A company that came through the link and topped up; no name once it's deleted.
     */
    ReferralRewardOut: {
      /** Name */
      name: string | null
      /**
       * Rewarded At
       * Format: date-time
       */
      rewarded_at: string
    }
    /**
     * ReportEmailIn
     * @description Who gets the candidate's report, and the PDF the page made, base64-encoded.
     */
    ReportEmailIn: {
      /**
       * Email
       * Format: email
       */
      email: string
      /** Pdf */
      pdf: string
    }
    /** ReportOut */
    ReportOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Reason */
      reason: string
      /** Comment */
      comment: string
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
    }
    /**
     * ReviewIn
     * @description Topic indices to keep, and optional free-text changes, as the generation service takes them.
     */
    ReviewIn: {
      /** Selected */
      selected: number[]
      /**
       * Instructions
       * @default
       */
      instructions: string
      /** Topics */
      topics?:
        | {
            [key: string]: unknown
          }[]
        | null
    }
    /** SessionSummary */
    SessionSummary: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Topic Title */
      topic_title: string
      /** Status */
      status: string
    }
    /** SkippedInvite */
    SkippedInvite: {
      /** Email */
      email: string
      /** Reason */
      reason: string
    }
    /**
     * SuggestedTalentOut
     * @description What a company sees of a suggested talent: their name, LinkedIn and first-round grade on
     *     a practice test for a similar role. Nothing else.
     */
    SuggestedTalentOut: {
      /** Name */
      name: string
      /** Url */
      url: string
      /** Grade */
      grade: number
    }
    /** TitleIn */
    TitleIn: {
      /** Title */
      title: string
    }
    /** TopicLimitIn */
    TopicLimitIn: {
      /** Limit */
      limit: number
    }
    /** TopicOut */
    TopicOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Title */
      title: string
      /**
       * Subtopics
       * @default []
       */
      subtopics: string[]
      /** Question Count */
      question_count: number
      /** Question Limit */
      question_limit: number
    }
    /**
     * UserCompaniesOut
     * @description Every company the user is a member of, for the notifications service.
     */
    UserCompaniesOut: {
      /** Company Ids */
      company_ids: string[]
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
      /** Input */
      input?: unknown
      /** Context */
      ctx?: Record<string, never>
    }
    /** VerificationOut */
    VerificationOut: {
      /** Website Domain */
      website_domain: string | null
      /** Verified Domain */
      verified_domain: string | null
    }
    /**
     * WebsiteIn
     * @description The company's website as typed; empty removes it, and the verification with it.
     */
    WebsiteIn: {
      /**
       * Website
       * @default
       */
      website: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  list_companies_companies_get: {
    parameters: {
      query?: {
        offset?: number
        limit?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["CompanyOut"][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  create_company_companies_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["CompanyCreate"]
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["CompanyOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  list_credits_companies_credits_get: {
    parameters: {
      query?: {
        offset?: number
        limit?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["CompanyBalanceOut"][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_company_companies__company_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        company_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["CompanyOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  delete_company_companies__company_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        company_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_credits_companies__company_id__credits_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        company_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["CompanyCreditsOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_referral_companies__company_id__referral_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        company_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ReferralOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  rename_company_companies__company_id__name_patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        company_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["CompanyRename"]
      }
    }
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_auto_top_up_companies__company_id__auto_top_up_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        company_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["AutoTopUpOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  turn_on_companies__company_id__auto_top_up_put: {
    parameters: {
      query?: never
      header?: never
      path: {
        company_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["AutoTopUpIn"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["AutoTopUpOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  turn_off_companies__company_id__auto_top_up_delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        company_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  list_members_members_get: {
    parameters: {
      query: {
        company_id: string
        offset?: number
        limit?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["MemberOut"][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  invite_admin_members_post: {
    parameters: {
      query: {
        company_id: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["MemberIn"]
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["MemberOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_admin_invite_members_invites__token__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        token: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["AdminInviteOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  accept_admin_invite_members_invites__token__accept_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        token: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  list_interviews_interviews_get: {
    parameters: {
      query: {
        company_id: string
        offset?: number
        limit?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["InterviewOut"][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  create_interview_interviews_post: {
    parameters: {
      query: {
        company_id: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["InterviewCreate"]
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["InterviewOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  create_from_template_interviews_from_template_post: {
    parameters: {
      query: {
        company_id: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["InterviewFromTemplate"]
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["InterviewOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_interview_interviews__interview_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        interview_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["InterviewDetail"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  delete_interview_interviews__interview_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        interview_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  update_settings_interviews__interview_id__settings_patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        interview_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["InterviewSettings"]
      }
    }
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  rename_interview_interviews__interview_id__title_patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        interview_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["TitleIn"]
      }
    }
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  preview_interview_interviews__interview_id__preview_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        interview_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["PreviewOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  list_candidates_interviews__interview_id__candidates_get: {
    parameters: {
      query?: {
        sort?: components["schemas"]["CandidateSort"]
        q?: string
        status?: components["schemas"]["CandidateFilter"] | null
        offset?: number
        limit?: number
      }
      header?: never
      path: {
        interview_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["CandidateOut"][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  invite_candidate_interviews__interview_id__candidates_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        interview_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["CandidateIn"]
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["CandidateOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  candidate_filters_interviews_candidates_filters_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["CandidateFiltersOut"]
        }
      }
    }
  }
  candidate_scorecard_interviews__interview_id__candidates__invite_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        interview_id: string
        invite_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            [key: string]: unknown
          }
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  revoke_candidate_interviews__interview_id__candidates__invite_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        interview_id: string
        invite_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  set_extra_time_interviews__interview_id__candidates__invite_id__extra_time_put: {
    parameters: {
      query?: never
      header?: never
      path: {
        interview_id: string
        invite_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["ExtraTimeIn"]
      }
    }
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  invite_many_interviews__interview_id__candidates_bulk_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        interview_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["BulkInviteIn"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["BulkInviteOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_generation_interviews__interview_id__generation_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        interview_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            [key: string]: unknown
          }
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  review_generation_interviews__interview_id__generation_review_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        interview_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReviewIn"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            [key: string]: unknown
          }
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  retry_generation_interviews__interview_id__generation_retry_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        interview_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            [key: string]: unknown
          }
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  cancel_generation_interviews__interview_id__generation_cancel_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        interview_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            [key: string]: unknown
          }
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  list_topic_questions_interviews__interview_id__topics__topic_id__questions_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        interview_id: string
        topic_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["QuestionText"][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  set_topic_limit_interviews__interview_id__topics__topic_id__limit_put: {
    parameters: {
      query?: never
      header?: never
      path: {
        interview_id: string
        topic_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["TopicLimitIn"]
      }
    }
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  regenerate_question_interviews__interview_id__questions__question_id__regenerate_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        interview_id: string
        question_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            [key: string]: unknown
          }
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  mark_wrong_interviews__interview_id__questions__question_id__wrong_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        interview_id: string
        question_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  list_question_reports_interviews__interview_id__questions__question_id__reports_get: {
    parameters: {
      query?: {
        offset?: number
        limit?: number
      }
      header?: never
      path: {
        interview_id: string
        question_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ReportOut"][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_invite_invites__token__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        token: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["InviteView"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  start_invite_invites__token__start_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        token: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["InviteStartOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  set_link_interviews__interview_id__link_put: {
    parameters: {
      query?: never
      header?: never
      path: {
        interview_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["LinkIn"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["LinkOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_link_links__token__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        token: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["LinkView"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  start_link_links__token__start_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        token: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["InviteStartOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_logo_companies__company_id__logo_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        company_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  set_logo_companies__company_id__logo_put: {
    parameters: {
      query?: never
      header?: never
      path: {
        company_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["LogoIn"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["LogoOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  remove_logo_companies__company_id__logo_delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        company_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  candidate_brand_candidates__invite_id__brand_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        invite_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["BrandOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  email_report_interviews__interview_id__candidates__invite_id__report_email_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        interview_id: string
        invite_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReportEmailIn"]
      }
    }
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  interview_report_interviews__interview_id__report_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        interview_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["InterviewReportOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  email_interview_report_interviews__interview_id__report_email_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        interview_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReportEmailIn"]
      }
    }
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  suggested_talents_interviews__interview_id__suggestions_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        interview_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["SuggestedTalentOut"][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  hide_talent_interviews__interview_id__suggestions_hide_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        interview_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["HideTalentIn"]
      }
    }
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  set_website_companies__company_id__website_put: {
    parameters: {
      query?: never
      header?: never
      path: {
        company_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["WebsiteIn"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["VerificationOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  delete_user_internal_users__user_id__delete: {
    parameters: {
      query: {
        email: string
      }
      header?: never
      path: {
        user_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  export_user_internal_users__user_id__export_get: {
    parameters: {
      query: {
        email: string
      }
      header?: never
      path: {
        user_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            [key: string]: unknown
          }
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  user_companies_internal_users__user_id__companies_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        user_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["UserCompaniesOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  invite_undelivered_internal_invites__invite_id__undelivered_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        invite_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  receive_event_internal_events_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["PushBody"]
      }
    }
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  retention_internal_schedules_retention_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  invite_expiry_internal_schedules_invite_expiry_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  invite_reminders_internal_schedules_invite_reminders_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  flush_outbox_internal_schedules_outbox_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  health_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            [key: string]: unknown
          }
        }
      }
    }
  }
  ready_ready_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            [key: string]: unknown
          }
        }
      }
    }
  }
}
