/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/generations": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Unfinished
     * @description Preparations still generating, waiting for topic review, or failed, newest first.
     */
    get: operations["list_unfinished_generations_get"]
    put?: never
    /** Create Generation */
    post: operations["create_generation_generations_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/generations/{generation_id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Generation */
    get: operations["get_generation_generations__generation_id__get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/generations/{generation_id}/review": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Review Generation */
    post: operations["review_generation_generations__generation_id__review_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/generations/{generation_id}/retry": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Retry */
    post: operations["retry_generations__generation_id__retry_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/generations/{generation_id}/cancel": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Cancel
     * @description Interviews are cancelled through companies, which also removes the interview.
     */
    post: operations["cancel_generations__generation_id__cancel_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/languages": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Languages
     * @description The languages kits and interviews can be generated in, for the "generate in" choice.
     */
    get: operations["list_languages_languages_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/generations": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Create Interview Generation
     * @description A company's interview; companies pays per candidate, so this one is free.
     */
    post: operations["create_interview_generation_internal_generations_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/generations/{generation_id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Interview Generation
     * @description For a caller that already checked the user belongs to the company.
     */
    get: operations["get_interview_generation_internal_generations__generation_id__get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/generations/{generation_id}/review": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Review Interview Generation
     * @description For a caller that already checked the user may manage the company's interviews.
     */
    post: operations["review_interview_generation_internal_generations__generation_id__review_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/generations/{generation_id}/retry": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Retry Interview Generation
     * @description For a caller that already checked the user may manage the company's interviews.
     */
    post: operations["retry_interview_generation_internal_generations__generation_id__retry_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/generations/{generation_id}/cancel": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Cancel Interview Generation
     * @description For a caller that already checked the user may manage the company's interviews.
     */
    post: operations["cancel_interview_generation_internal_generations__generation_id__cancel_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/questions/{question_id}/regenerate": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Regenerate Interview Question
     * @description For a caller that already checked the user may edit this set.
     */
    post: operations["regenerate_interview_question_internal_questions__question_id__regenerate_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/questions/{question_id}/verify": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Verify Question
     * @description The library flagged the question; the worker checks it and fixes or replaces it.
     */
    post: operations["verify_question_internal_questions__question_id__verify_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/users/{user_id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Delete User
     * @description Part of deleting an account (library coordinates it); safe to repeat.
     */
    delete: operations["delete_user_internal_users__user_id__delete"]
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/users/{user_id}/export": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Export User */
    get: operations["export_user_internal_users__user_id__export_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/titles/check": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Check
     * @description For library, before a kit is public: whether its title names a company.
     */
    post: operations["check_internal_titles_check_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/health": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Health */
    get: operations["health_health_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/ready": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Ready
     * @description Ready only once the database and Redis answer; Docker's healthcheck uses this.
     */
    get: operations["ready_ready_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** DraftTopic */
    DraftTopic: {
      /** Main Topic */
      main_topic: string
      /** Subtopics */
      subtopics: string[]
    }
    /** EditedTopic */
    EditedTopic: {
      /** Main Topic */
      main_topic: string
      /** Subtopics */
      subtopics: string[]
    }
    /** GenerationCreate */
    GenerationCreate: {
      /** Text */
      text: string
      /** @default preparation */
      kind: components["schemas"]["GenerationKind"]
      /** Company Id */
      company_id?: string | null
      /** Generate In */
      generate_in?:
        | (
            | "en"
            | "ru"
            | "uk"
            | "es"
            | "pt"
            | "de"
            | "fr"
            | "it"
            | "pl"
            | "nl"
            | "tr"
            | "ar"
            | "he"
            | "fa"
            | "ja"
            | "zh"
            | "ko"
            | "hi"
            | "id"
            | "th"
            | "vi"
            | "fil"
            | "et"
          )
        | null
    }
    /**
     * GenerationKind
     * @enum {string}
     */
    GenerationKind: "preparation" | "interview"
    /** GenerationOut */
    GenerationOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      kind: components["schemas"]["GenerationKind"]
      /** Company Id */
      company_id: string | null
      status: components["schemas"]["Status"]
      /** Topics */
      topics: components["schemas"]["DraftTopic"][] | null
      progress: components["schemas"]["GenerationProgress"] | null
      /** Preparation Id */
      preparation_id: string | null
      /** Error */
      error: string | null
      /** Language */
      language: string
      /** Free Kit */
      free_kit: boolean
      /**
       * Max Topics
       * @description How many topics the review may approve without instructions.
       */
      readonly max_topics: number
      /**
       * Max Subtopics
       * @description How many subtopics a topic may have when edited by hand during review.
       */
      readonly max_subtopics: number
    }
    /**
     * GenerationProgress
     * @description What the progress screen shows; the worker's own per-topic counters stay internal.
     */
    GenerationProgress: {
      /** Done */
      done: number
      /** Total */
      total: number
      /** Topics */
      topics?: number | null
      /** Topics Ready */
      topics_ready?: number | null
    }
    /**
     * GenerationSummary
     * @description An unfinished generation in a list, with the start of the goal it was made from.
     */
    GenerationSummary: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      status: components["schemas"]["Status"]
      /** Preview */
      preview: string
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][]
    }
    /**
     * InterviewGenerationCreate
     * @description From companies, once it has checked the user belongs to the company.
     */
    InterviewGenerationCreate: {
      /** Text */
      text: string
      /**
       * Company Id
       * Format: uuid
       */
      company_id: string
      /** Owner Uid */
      owner_uid: string
      /**
       * Language
       * @default en
       * @enum {string}
       */
      language:
        | "en"
        | "ru"
        | "uk"
        | "es"
        | "pt"
        | "de"
        | "fr"
        | "it"
        | "pl"
        | "nl"
        | "tr"
        | "ar"
        | "he"
        | "fa"
        | "ja"
        | "zh"
        | "ko"
        | "hi"
        | "id"
        | "th"
        | "vi"
        | "fil"
        | "et"
      /** Generate In */
      generate_in?:
        | (
            | "en"
            | "ru"
            | "uk"
            | "es"
            | "pt"
            | "de"
            | "fr"
            | "it"
            | "pl"
            | "nl"
            | "tr"
            | "ar"
            | "he"
            | "fa"
            | "ja"
            | "zh"
            | "ko"
            | "hi"
            | "id"
            | "th"
            | "vi"
            | "fil"
            | "et"
          )
        | null
    }
    /**
     * QualityFlag
     * @description Why the library sent a question to the verifier; mirrors the library's flags.
     * @enum {string}
     */
    QualityFlag: "wrong_key" | "rewrite" | "weak_options"
    /** RegenerateIn */
    RegenerateIn: {
      /** User Id */
      user_id: string
      /**
       * Set Id
       * Format: uuid
       */
      set_id: string
    }
    /** RegeneratedOut */
    RegeneratedOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Text */
      text: string
    }
    /** ReviewRequest */
    ReviewRequest: {
      /** Selected */
      selected: number[]
      /**
       * Instructions
       * @default
       */
      instructions: string
      /** Topics */
      topics?: components["schemas"]["EditedTopic"][] | null
    }
    /**
     * Status
     * @enum {string}
     */
    Status:
      "queued" | "running" | "awaiting_review" | "done" | "failed" | "cancelled"
    /** TitleCheckIn */
    TitleCheckIn: {
      /** Title */
      title: string
    }
    /** TitleCheckOut */
    TitleCheckOut: {
      /**
       * Has Company
       * @description True when the title names a company or organization, not just its products
       */
      has_company: boolean
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
      /** Input */
      input?: unknown
      /** Context */
      ctx?: Record<string, never>
    }
    /** VerifyIn */
    VerifyIn: {
      flag: components["schemas"]["QualityFlag"]
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  list_unfinished_generations_get: {
    parameters: {
      query?: {
        offset?: number
        limit?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["GenerationSummary"][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  create_generation_generations_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenerationCreate"]
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["GenerationOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_generation_generations__generation_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        generation_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["GenerationOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  review_generation_generations__generation_id__review_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        generation_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReviewRequest"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["GenerationOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  retry_generations__generation_id__retry_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        generation_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["GenerationOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  cancel_generations__generation_id__cancel_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        generation_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["GenerationOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  list_languages_languages_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": string[]
        }
      }
    }
  }
  create_interview_generation_internal_generations_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["InterviewGenerationCreate"]
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["GenerationOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_interview_generation_internal_generations__generation_id__get: {
    parameters: {
      query: {
        company_id: string
      }
      header?: never
      path: {
        generation_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["GenerationOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  review_interview_generation_internal_generations__generation_id__review_post: {
    parameters: {
      query: {
        company_id: string
      }
      header?: never
      path: {
        generation_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReviewRequest"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["GenerationOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  retry_interview_generation_internal_generations__generation_id__retry_post: {
    parameters: {
      query: {
        company_id: string
      }
      header?: never
      path: {
        generation_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["GenerationOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  cancel_interview_generation_internal_generations__generation_id__cancel_post: {
    parameters: {
      query: {
        company_id: string
      }
      header?: never
      path: {
        generation_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["GenerationOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  regenerate_interview_question_internal_questions__question_id__regenerate_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        question_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegenerateIn"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["RegeneratedOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  verify_question_internal_questions__question_id__verify_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        question_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["VerifyIn"]
      }
    }
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  delete_user_internal_users__user_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        user_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  export_user_internal_users__user_id__export_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        user_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            [key: string]: unknown
          }
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  check_internal_titles_check_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["TitleCheckIn"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["TitleCheckOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  health_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            [key: string]: unknown
          }
        }
      }
    }
  }
  ready_ready_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            [key: string]: unknown
          }
        }
      }
    }
  }
}
