/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/me": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Me */
    get: operations["me_me_get"]
    put?: never
    post?: never
    /**
     * Delete Me
     * @description Deletes the account and everything about it. A company the user alone owns goes too.
     */
    delete: operations["delete_me_me_delete"]
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/me/settings": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * Update Settings
     * @description Takes effect once the frontend refreshes the user's ID token.
     */
    put: operations["update_settings_me_settings_put"]
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/me/export": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Export Me
     * @description Everything prepza holds about the user, as one JSON file to download.
     */
    get: operations["export_me_me_export_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/superadmin/templates": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Templates */
    get: operations["list_templates_superadmin_templates_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/superadmin/templates/{template_id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Template Detail */
    get: operations["get_template_detail_superadmin_templates__template_id__get"]
    put?: never
    post?: never
    /** Delete Template */
    delete: operations["delete_template_superadmin_templates__template_id__delete"]
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/superadmin/templates/{template_id}/title": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Rename Template */
    patch: operations["rename_template_superadmin_templates__template_id__title_patch"]
    trace?: never
  }
  "/superadmin/templates/{template_id}/topics/{topic_id}/questions": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Topic Questions
     * @description A topic's questions with their options and feedback counts.
     */
    get: operations["list_topic_questions_superadmin_templates__template_id__topics__topic_id__questions_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/superadmin/templates/{template_id}/questions/{question_id}/reports": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Question Reports */
    get: operations["list_question_reports_superadmin_templates__template_id__questions__question_id__reports_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/superadmin/templates/{template_id}/questions/{question_id}/wrong": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Mark Wrong */
    post: operations["mark_wrong_superadmin_templates__template_id__questions__question_id__wrong_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/superadmin/quality/flagged": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Flagged */
    get: operations["list_flagged_superadmin_quality_flagged_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/superadmin/quality/replaced": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Replaced */
    get: operations["list_replaced_superadmin_quality_replaced_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/superadmin/quality/{question_id}/fix": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Fix Now
     * @description Sends the question to the verifier at once; it fixes or replaces it in the background.
     */
    post: operations["fix_now_superadmin_quality__question_id__fix_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/superadmin/quality/{question_id}/dismiss": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Dismiss
     * @description The flag is wrong: the question stays, and isn't flagged again until it changes.
     */
    post: operations["dismiss_superadmin_quality__question_id__dismiss_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/superadmin/quality/{question_id}/reports": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Reports
     * @description A flagged question's reports, newest first.
     */
    get: operations["list_reports_superadmin_quality__question_id__reports_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/superadmin/quality/revisions/{revision_id}/reports": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Revision Reports
     * @description The reports a replaced question had, as kept with its old content, newest first.
     */
    get: operations["list_revision_reports_superadmin_quality_revisions__revision_id__reports_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/templates/filters": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Template Filters */
    get: operations["template_filters_templates_filters_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/templates": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Templates */
    get: operations["list_templates_templates_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/templates/{template_id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Template
     * @description A template's topics and subtopics, to review before using it; its questions stay hidden.
     */
    get: operations["get_template_templates__template_id__get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/interviews": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Create Interview
     * @description A retried save from the same generation returns the set it already made.
     */
    post: operations["create_interview_internal_interviews_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/templates": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Create Template
     * @description A retried save from the same generation returns the template it already made.
     */
    post: operations["create_template_internal_templates_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/templates/{template_id}/copy": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Copy Template
     * @description For companies: a company's own test made from a template, with no generation.
     */
    post: operations["copy_template_internal_templates__template_id__copy_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/interviews/{set_id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Delete Interview
     * @description Deletes an interview set; safe to repeat.
     */
    delete: operations["delete_interview_internal_interviews__set_id__delete"]
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/sets/{set_id}/title": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Rename Set */
    patch: operations["rename_set_internal_sets__set_id__title_patch"]
    trace?: never
  }
  "/internal/sets/{set_id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Set */
    get: operations["get_set_internal_sets__set_id__get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/sets/{set_id}/content": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Set Content */
    get: operations["get_set_content_internal_sets__set_id__content_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/sets/{set_id}/topics/{topic_id}/questions": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Topic Questions
     * @description One topic's questions in a set, with their options and feedback counts.
     */
    get: operations["list_topic_questions_internal_sets__set_id__topics__topic_id__questions_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/sets/{set_id}/questions/{question_id}/reports": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Question Reports */
    get: operations["list_question_reports_internal_sets__set_id__questions__question_id__reports_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/questions/{question_id}/context": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Question Context */
    get: operations["get_question_context_internal_questions__question_id__context_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/questions/{question_id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /** Replace Question */
    put: operations["replace_question_internal_questions__question_id__put"]
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/schedules/outbox": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Flush Outbox
     * @description Every minute, from Cloud Scheduler: publishes events that weren't published right after
     *     their change.
     */
    post: operations["flush_outbox_internal_schedules_outbox_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/schedules/bank": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Move Bank Stages
     * @description Daily, from Cloud Scheduler: bank questions move one way, private to retiring to
     *     revealed (constants/sets.py Stage).
     */
    post: operations["move_bank_stages_internal_schedules_bank_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/events": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Receive Event
     * @description Pub/Sub pushes every event here. A failure answers with an error, so Pub/Sub retries it,
     *     and moves it to the dead-letter topic after the subscription's maximum attempts.
     */
    post: operations["receive_event_internal_events_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/questions/{question_id}/rating": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Rating
     * @description For callers that already checked the user may see this question, e.g. a candidate.
     */
    get: operations["get_rating_internal_questions__question_id__rating_get"]
    /** Rate */
    put: operations["rate_internal_questions__question_id__rating_put"]
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/questions/{question_id}/reports/mine": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** My Report */
    get: operations["my_report_internal_questions__question_id__reports_mine_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/questions/{question_id}/reports": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Report */
    post: operations["report_internal_questions__question_id__reports_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/templates/{template_id}/practice": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Practice Content
     * @description The template's revealed questions, with answers, by topic; topics without any are left
     *     out. Rounds picks each practice round's questions from them.
     */
    get: operations["practice_content_internal_templates__template_id__practice_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/questions/{question_id}/quality": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Quality */
    get: operations["get_quality_internal_questions__question_id__quality_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/questions/{question_id}/keep": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Keep
     * @description The verifier found nothing wrong: serve the question again and stop flagging it.
     */
    post: operations["keep_internal_questions__question_id__keep_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/questions/{question_id}/wrong": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Mark Wrong
     * @description For companies, once it has checked the question is in the company's test.
     */
    post: operations["mark_wrong_internal_questions__question_id__wrong_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/reuse": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Find Reusable
     * @description Proven private bank questions on a similar topic, for a new generation.
     */
    post: operations["find_reusable_internal_reuse_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/embeddings/missing": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Missing Embeddings
     * @description Template topics without an embedding, for generation's embed_templates job.
     */
    get: operations["list_missing_embeddings_internal_embeddings_missing_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/embeddings": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /** Save Embeddings */
    put: operations["save_embeddings_internal_embeddings_put"]
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/health": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Health */
    get: operations["health_health_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/ready": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Ready
     * @description Ready only once the database and Redis answer; Docker's healthcheck uses this.
     */
    get: operations["ready_ready_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** CreatedOut */
    CreatedOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string
    }
    /**
     * FlaggedQuestionOut
     * @description A question flagged now, for the admin zone's quality tab.
     */
    FlaggedQuestionOut: {
      /**
       * Question Id
       * Format: uuid
       */
      question_id: string
      /** Text */
      text: string
      /** Options */
      options: components["schemas"]["OptionIn"][]
      /** Flag */
      flag: string
      /** Actionable */
      actionable: boolean
      /** Answers */
      answers: number
      /** Correct */
      correct: number
      /** Reports */
      reports: number
      /** Set Title */
      set_title: string
      /** Set Kind */
      set_kind: string
      /**
       * At
       * Format: date-time
       */
      at: string
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][]
    }
    /** InternalRatingIn */
    InternalRatingIn: {
      /**
       * Value
       * @enum {integer}
       */
      value: -1 | 1
      /** User Id */
      user_id: string
    }
    /** InternalReportIn */
    InternalReportIn: {
      reason: components["schemas"]["ReportReason"]
      /**
       * Comment
       * @default
       */
      comment: string
      /** User Id */
      user_id: string
    }
    /**
     * MeOut
     * @description The signed-in user, and whether they may open the superadmin pages.
     */
    MeOut: {
      /** Uid */
      uid: string
      /** Email */
      email: string
      /** Email Verified */
      email_verified: boolean
      /** Name */
      name?: string | null
      /**
       * Language
       * @default en
       * @enum {string}
       */
      language:
        | "en"
        | "ru"
        | "uk"
        | "es"
        | "pt"
        | "de"
        | "fr"
        | "it"
        | "pl"
        | "nl"
        | "tr"
        | "ar"
        | "he"
        | "fa"
        | "ja"
        | "zh"
        | "ko"
        | "hi"
        | "id"
        | "th"
        | "vi"
        | "fil"
        | "et"
      /** Is Superadmin */
      is_superadmin: boolean
    }
    /** MyReportOut */
    MyReportOut: {
      /** Reported */
      reported: boolean
    }
    /** OptionIn */
    OptionIn: {
      /** Answer */
      answer: string
      /** Correct */
      correct: boolean
    }
    /**
     * PreparationIn
     * @description A generated test, as generation saves it in library.
     */
    PreparationIn: {
      /**
       * Generation Id
       * Format: uuid
       */
      generation_id: string
      /** Owner Uid */
      owner_uid: string
      /** Source Text */
      source_text: string
      /** Title */
      title: string
      /** Level */
      level: string
      /** Requirements */
      requirements: string[]
      /** Topics */
      topics: components["schemas"]["TopicIn"][]
      /**
       * Language
       * @default en
       */
      language: string
    }
    /**
     * PushBody
     * @description What Pub/Sub sends to a push endpoint.
     */
    PushBody: {
      message: components["schemas"]["PushMessage"]
      /** Subscription */
      subscription: string
    }
    /** PushMessage */
    PushMessage: {
      /**
       * Data
       * @default
       */
      data: string
      /**
       * Attributes
       * @default {}
       */
      attributes: {
        [key: string]: string
      }
      /** Messageid */
      messageId: string
    }
    /**
     * QuestionContext
     * @description What the generator needs to replace a question without repeating its topic.
     */
    QuestionContext: {
      /**
       * Set Id
       * Format: uuid
       */
      set_id: string
      /** Kind */
      kind: string
      /** Owner Id */
      owner_id: string
      /** Level */
      level: string
      /** Language */
      language: string
      /** Topic */
      topic: string
      /** Subtopics */
      subtopics: string[]
      /** Existing */
      existing: string[]
    }
    /** QuestionIn */
    QuestionIn: {
      /** Text */
      text: string
      /** Options */
      options: components["schemas"]["OptionIn"][]
      /** Source Id */
      source_id?: string | null
    }
    /** QuestionOut */
    QuestionOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Text */
      text: string
      /** Options */
      options: components["schemas"]["OptionIn"][]
    }
    /**
     * QuestionQuality
     * @description What the verifier looks at: the question, how it's answered and what users reported.
     */
    QuestionQuality: {
      /** Text */
      text: string
      /** Options */
      options: components["schemas"]["OptionIn"][]
      /** Answers */
      answers: number
      /** Option Picks */
      option_picks: {
        [key: string]: number
      }
      /** Reports */
      reports: components["schemas"]["ReportNote"][]
    }
    /** QuestionRatingOut */
    QuestionRatingOut: {
      /** Value */
      value?: (-1 | 1) | null
    }
    /** QuestionReplace */
    QuestionReplace: {
      /** Text */
      text: string
      /** Options */
      options: components["schemas"]["OptionIn"][]
    }
    /**
     * QuestionText
     * @description A question as its owner manages it: text, answer options and feedback counts.
     */
    QuestionText: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Text */
      text: string
      /** Options */
      options: components["schemas"]["OptionIn"][]
      /**
       * Likes
       * @default 0
       */
      likes: number
      /**
       * Dislikes
       * @default 0
       */
      dislikes: number
      /**
       * Reports
       * @default 0
       */
      reports: number
    }
    /**
     * ReplacedQuestionOut
     * @description A question's old content, kept when it was replaced.
     */
    ReplacedQuestionOut: {
      /**
       * Revision Id
       * Format: uuid
       */
      revision_id: string
      /**
       * Question Id
       * Format: uuid
       */
      question_id: string
      /** Text */
      text: string
      /** Options */
      options: components["schemas"]["OptionIn"][]
      /** Answers */
      answers: number
      /** Correct */
      correct: number
      /** Reports */
      reports: number
      /** Set Title */
      set_title: string
      /** Set Kind */
      set_kind: string
      /**
       * At
       * Format: date-time
       */
      at: string
    }
    /** ReportNote */
    ReportNote: {
      /** Reason */
      reason: string
      /** Comment */
      comment: string
    }
    /**
     * ReportOut
     * @description A report without the reporter's identity.
     */
    ReportOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Reason */
      reason: string
      /** Comment */
      comment: string
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
    }
    /**
     * ReportReason
     * @enum {string}
     */
    ReportReason: "wrong_answer" | "unclear" | "off_topic" | "other"
    /** ReuseIn */
    ReuseIn: {
      /** Embedding */
      embedding: number[]
      /** Level */
      level: string
      /**
       * Language
       * @default en
       */
      language: string
      /** Count */
      count: number
    }
    /** ReusedQuestion */
    ReusedQuestion: {
      /**
       * Source Id
       * Format: uuid
       */
      source_id: string
      /** Text */
      text: string
      /** Options */
      options: components["schemas"]["OptionIn"][]
    }
    /**
     * SetContent
     * @description Internal: every question of an interview, with answers.
     */
    SetContent: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Title */
      title: string
      /** Topics */
      topics: components["schemas"]["SetTopicOut"][]
    }
    /** SetOut */
    SetOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Kind */
      kind: string
      /** Owner Id */
      owner_id: string
      /** Title */
      title: string
      /** Level */
      level: string
      /** Topics */
      topics: components["schemas"]["TopicOut"][]
    }
    /** SetTopicOut */
    SetTopicOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Title */
      title: string
      /** Questions */
      questions: components["schemas"]["QuestionOut"][]
    }
    /** SettingsIn */
    SettingsIn: {
      /**
       * Language
       * @enum {string}
       */
      language:
        | "en"
        | "ru"
        | "uk"
        | "es"
        | "pt"
        | "de"
        | "fr"
        | "it"
        | "pl"
        | "nl"
        | "tr"
        | "ar"
        | "he"
        | "fa"
        | "ja"
        | "zh"
        | "ko"
        | "hi"
        | "id"
        | "th"
        | "vi"
        | "fil"
        | "et"
    }
    /** TemplateCopyIn */
    TemplateCopyIn: {
      /** Company Id */
      company_id: string
    }
    /**
     * TemplateCopyOut
     * @description The company's new test set.
     */
    TemplateCopyOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Title */
      title: string
      /** Language */
      language: string
    }
    /**
     * TemplateFiltersOut
     * @description What the template list can be filtered by.
     */
    TemplateFiltersOut: {
      /** Levels */
      levels: string[]
      /** Languages */
      languages: string[]
    }
    /** TemplateOut */
    TemplateOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Title */
      title: string
      /** Level */
      level: string
      /** Language */
      language: string
      /** Topic Count */
      topic_count: number
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Topics */
      topics: components["schemas"]["TopicOut"][]
    }
    /**
     * TemplateSummary
     * @description A template in the admin's list.
     */
    TemplateSummary: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Title */
      title: string
      /** Level */
      level: string
      /** Language */
      language: string
      /** Topic Count */
      topic_count: number
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
    }
    /** TitleIn */
    TitleIn: {
      /** Title */
      title: string
    }
    /** TopicEmbedding */
    TopicEmbedding: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Embedding */
      embedding: number[]
    }
    /** TopicIn */
    TopicIn: {
      /** Title */
      title: string
      /** Subtopics */
      subtopics: string[]
      /** Questions */
      questions: components["schemas"]["QuestionIn"][]
      /** Embedding */
      embedding?: number[] | null
    }
    /** TopicOut */
    TopicOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Title */
      title: string
      /** Subtopics */
      subtopics: string[]
      /** Question Count */
      question_count: number
    }
    /** TopicToEmbed */
    TopicToEmbed: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Title */
      title: string
      /** Subtopics */
      subtopics: string[]
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
      /** Input */
      input?: unknown
      /** Context */
      ctx?: Record<string, never>
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  me_me_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["MeOut"]
        }
      }
    }
  }
  delete_me_me_delete: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  update_settings_me_settings_put: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["SettingsIn"]
      }
    }
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  export_me_me_export_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            [key: string]: unknown
          }
        }
      }
    }
  }
  list_templates_superadmin_templates_get: {
    parameters: {
      query?: {
        q?: string
        level?: ("basic" | "medium" | "hard") | null
        language?:
          | (
              | "en"
              | "ru"
              | "uk"
              | "es"
              | "pt"
              | "de"
              | "fr"
              | "it"
              | "pl"
              | "nl"
              | "tr"
              | "ar"
              | "he"
              | "fa"
              | "ja"
              | "zh"
              | "ko"
              | "hi"
              | "id"
              | "th"
              | "vi"
              | "fil"
              | "et"
            )[]
          | null
        offset?: number
        limit?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["TemplateSummary"][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_template_detail_superadmin_templates__template_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        template_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["TemplateOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  delete_template_superadmin_templates__template_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        template_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  rename_template_superadmin_templates__template_id__title_patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        template_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["TitleIn"]
      }
    }
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  list_topic_questions_superadmin_templates__template_id__topics__topic_id__questions_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        template_id: string
        topic_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["QuestionText"][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  list_question_reports_superadmin_templates__template_id__questions__question_id__reports_get: {
    parameters: {
      query?: {
        offset?: number
        limit?: number
      }
      header?: never
      path: {
        template_id: string
        question_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ReportOut"][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  mark_wrong_superadmin_templates__template_id__questions__question_id__wrong_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        template_id: string
        question_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  list_flagged_superadmin_quality_flagged_get: {
    parameters: {
      query?: {
        offset?: number
        limit?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["FlaggedQuestionOut"][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  list_replaced_superadmin_quality_replaced_get: {
    parameters: {
      query?: {
        offset?: number
        limit?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ReplacedQuestionOut"][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  fix_now_superadmin_quality__question_id__fix_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        question_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  dismiss_superadmin_quality__question_id__dismiss_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        question_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  list_reports_superadmin_quality__question_id__reports_get: {
    parameters: {
      query?: {
        offset?: number
        limit?: number
      }
      header?: never
      path: {
        question_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ReportOut"][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  list_revision_reports_superadmin_quality_revisions__revision_id__reports_get: {
    parameters: {
      query?: {
        offset?: number
        limit?: number
      }
      header?: never
      path: {
        revision_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ReportOut"][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  template_filters_templates_filters_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["TemplateFiltersOut"]
        }
      }
    }
  }
  list_templates_templates_get: {
    parameters: {
      query?: {
        q?: string
        level?: ("basic" | "medium" | "hard") | null
        language?:
          | (
              | "en"
              | "ru"
              | "uk"
              | "es"
              | "pt"
              | "de"
              | "fr"
              | "it"
              | "pl"
              | "nl"
              | "tr"
              | "ar"
              | "he"
              | "fa"
              | "ja"
              | "zh"
              | "ko"
              | "hi"
              | "id"
              | "th"
              | "vi"
              | "fil"
              | "et"
            )[]
          | null
        offset?: number
        limit?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["TemplateSummary"][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_template_templates__template_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        template_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["TemplateOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  create_interview_internal_interviews_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["PreparationIn"]
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["CreatedOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  create_template_internal_templates_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["PreparationIn"]
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["CreatedOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  copy_template_internal_templates__template_id__copy_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        template_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["TemplateCopyIn"]
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["TemplateCopyOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  delete_interview_internal_interviews__set_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        set_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  rename_set_internal_sets__set_id__title_patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        set_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["TitleIn"]
      }
    }
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_set_internal_sets__set_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        set_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["SetOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_set_content_internal_sets__set_id__content_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        set_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["SetContent"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  list_topic_questions_internal_sets__set_id__topics__topic_id__questions_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        set_id: string
        topic_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["QuestionText"][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  list_question_reports_internal_sets__set_id__questions__question_id__reports_get: {
    parameters: {
      query?: {
        offset?: number
        limit?: number
      }
      header?: never
      path: {
        set_id: string
        question_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ReportOut"][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_question_context_internal_questions__question_id__context_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        question_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["QuestionContext"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  replace_question_internal_questions__question_id__put: {
    parameters: {
      query?: never
      header?: never
      path: {
        question_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["QuestionReplace"]
      }
    }
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  flush_outbox_internal_schedules_outbox_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  move_bank_stages_internal_schedules_bank_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  receive_event_internal_events_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["PushBody"]
      }
    }
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_rating_internal_questions__question_id__rating_get: {
    parameters: {
      query: {
        user_id: string
      }
      header?: never
      path: {
        question_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["QuestionRatingOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  rate_internal_questions__question_id__rating_put: {
    parameters: {
      query?: never
      header?: never
      path: {
        question_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["InternalRatingIn"]
      }
    }
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  my_report_internal_questions__question_id__reports_mine_get: {
    parameters: {
      query: {
        user_id: string
      }
      header?: never
      path: {
        question_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["MyReportOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  report_internal_questions__question_id__reports_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        question_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["InternalReportIn"]
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  practice_content_internal_templates__template_id__practice_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        template_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["SetContent"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_quality_internal_questions__question_id__quality_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        question_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["QuestionQuality"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  keep_internal_questions__question_id__keep_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        question_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  mark_wrong_internal_questions__question_id__wrong_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        question_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  find_reusable_internal_reuse_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReuseIn"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ReusedQuestion"][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  list_missing_embeddings_internal_embeddings_missing_get: {
    parameters: {
      query?: {
        limit?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["TopicToEmbed"][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  save_embeddings_internal_embeddings_put: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["TopicEmbedding"][]
      }
    }
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  health_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            [key: string]: unknown
          }
        }
      }
    }
  }
  ready_ready_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            [key: string]: unknown
          }
        }
      }
    }
  }
}
