/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/me": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Me */
    get: operations["me_me_get"]
    put?: never
    post?: never
    /**
     * Delete Me
     * @description Deletes the account and everything about it. A company the user alone owns goes too.
     */
    delete: operations["delete_me_me_delete"]
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/me/export": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Export Me
     * @description Everything prepza holds about the user, as one JSON file to download.
     */
    get: operations["export_me_me_export_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/preparations": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Mine
     * @description The user's own and joined preparations together, newest first, a page at a time.
     */
    get: operations["list_mine_preparations_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/preparations/topics/{topic_id}/questions": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Topic Questions
     * @description Question text for a topic the viewer can already open.
     */
    get: operations["list_topic_questions_preparations_topics__topic_id__questions_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/preparations/{preparation_id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Preparation
     * @description Owners and joined users see their preparation; anyone sees a public one.
     */
    get: operations["get_preparation_preparations__preparation_id__get"]
    put?: never
    post?: never
    /**
     * Delete Preparation
     * @description Only the owner deletes a preparation; everyone who joined it loses access too.
     *
     *     Practice data goes first, so a failure there leaves the preparation in place to retry.
     */
    delete: operations["delete_preparation_preparations__preparation_id__delete"]
    options?: never
    head?: never
    /** Update Visibility */
    patch: operations["update_visibility_preparations__preparation_id__patch"]
    trace?: never
  }
  "/preparations/{preparation_id}/title": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /**
     * Update Title
     * @description Only the preparation's owner can rename it.
     */
    patch: operations["update_title_preparations__preparation_id__title_patch"]
    trace?: never
  }
  "/preparations/{preparation_id}/join": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Join
     * @description Joins a public preparation; owners and members are already in.
     */
    post: operations["join_preparations__preparation_id__join_post"]
    /** Leave */
    delete: operations["leave_preparations__preparation_id__join_delete"]
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/preparations/{preparation_id}/rating": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * Rate
     * @description Joined users rate the preparation; owners can't rate their own.
     */
    put: operations["rate_preparations__preparation_id__rating_put"]
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/preparations/{preparation_id}/shares": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Shares */
    get: operations["list_shares_preparations__preparation_id__shares_get"]
    put?: never
    /**
     * Share
     * @description Invites one email; sharing the same email again resends the invite.
     */
    post: operations["share_preparations__preparation_id__shares_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/shares/{token}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Share */
    get: operations["get_share_shares__token__get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/shares/{token}/accept": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Accept Share
     * @description Only the invited email can accept, so a forwarded link is useless to anyone else.
     */
    post: operations["accept_share_shares__token__accept_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/questions/{question_id}/regenerate": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Regenerate
     * @description Only the owner of a preparation replaces its questions; generation writes the new one.
     */
    post: operations["regenerate_questions__question_id__regenerate_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/questions/{question_id}/rating": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Rating */
    get: operations["get_rating_questions__question_id__rating_get"]
    /** Rate */
    put: operations["rate_questions__question_id__rating_put"]
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/questions/{question_id}/reports": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Reports
     * @description Only the preparation owner reads reports; interview reports go through companies.
     */
    get: operations["list_reports_questions__question_id__reports_get"]
    put?: never
    /** Report */
    post: operations["report_questions__question_id__reports_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/questions/{question_id}/reports/mine": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** My Report */
    get: operations["my_report_questions__question_id__reports_mine_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/library": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Search Library
     * @description Public preparations, a page at a time; no login needed.
     */
    get: operations["search_library_library_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/preparations": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Create Preparation
     * @description A retried save from the same generation returns the set it already made.
     */
    post: operations["create_preparation_internal_preparations_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/interviews": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Create Interview
     * @description A retried save from the same generation returns the set it already made.
     */
    post: operations["create_interview_internal_interviews_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/interviews/{set_id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Delete Interview
     * @description Deletes an interview set; safe to repeat. Never deletes a user's preparation.
     */
    delete: operations["delete_interview_internal_interviews__set_id__delete"]
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/sets/{set_id}/title": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Rename Set */
    patch: operations["rename_set_internal_sets__set_id__title_patch"]
    trace?: never
  }
  "/internal/sets/{set_id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Set */
    get: operations["get_set_internal_sets__set_id__get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/sets/{set_id}/content": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Set Content */
    get: operations["get_set_content_internal_sets__set_id__content_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/sets/{set_id}/question-texts": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Question Texts
     * @description Current text per question id, so callers can tell a re-generated question apart.
     */
    get: operations["list_question_texts_internal_sets__set_id__question_texts_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/sets/{set_id}/topics/{topic_id}/questions": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Topic Questions
     * @description Question text and feedback counts of one topic in a set, without answers.
     */
    get: operations["list_topic_questions_internal_sets__set_id__topics__topic_id__questions_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/sets/{set_id}/questions/{question_id}/reports": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Question Reports */
    get: operations["list_question_reports_internal_sets__set_id__questions__question_id__reports_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/questions/{question_id}/context": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Question Context */
    get: operations["get_question_context_internal_questions__question_id__context_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/questions/{question_id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /** Replace Question */
    put: operations["replace_question_internal_questions__question_id__put"]
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/topics/{topic_id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Topic Questions
     * @description Questions of a topic the user owns or joined, for starting a round.
     */
    get: operations["get_topic_questions_internal_topics__topic_id__get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/schedules/outbox": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Flush Outbox
     * @description Every minute, from Cloud Scheduler: publishes events that weren't published right after
     *     their change.
     */
    post: operations["flush_outbox_internal_schedules_outbox_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/events": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Receive Event
     * @description Pub/Sub pushes every event here. A failure answers with an error, so Pub/Sub retries it,
     *     and moves it to the dead-letter topic after the subscription's maximum attempts.
     */
    post: operations["receive_event_internal_events_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/questions/{question_id}/rating": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Rating
     * @description For callers that already checked the user may see this question, e.g. a candidate.
     */
    get: operations["get_rating_internal_questions__question_id__rating_get"]
    /** Rate */
    put: operations["rate_internal_questions__question_id__rating_put"]
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/questions/{question_id}/reports/mine": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** My Report */
    get: operations["my_report_internal_questions__question_id__reports_mine_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/questions/{question_id}/reports": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Report */
    post: operations["report_internal_questions__question_id__reports_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/questions/{question_id}/quality": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Quality */
    get: operations["get_quality_internal_questions__question_id__quality_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/questions/{question_id}/keep": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Keep
     * @description The verifier found nothing wrong: serve the question again and stop flagging it.
     */
    post: operations["keep_internal_questions__question_id__keep_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/reuse": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Find Reusable
     * @description Proven questions from public preparations on a similar topic, for a new generation.
     */
    post: operations["find_reusable_internal_reuse_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/embeddings/missing": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Missing Embeddings
     * @description Preparation topics saved before embeddings existed, for the one-off backfill.
     */
    get: operations["list_missing_embeddings_internal_embeddings_missing_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/embeddings": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /** Save Embeddings */
    put: operations["save_embeddings_internal_embeddings_put"]
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/shares/{share_id}/undelivered": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Share Undelivered
     * @description Notifications reports a bounced or spam-flagged share email; safe to repeat.
     */
    post: operations["share_undelivered_internal_shares__share_id__undelivered_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/health": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Health */
    get: operations["health_health_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/ready": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Ready
     * @description Ready only once the database and Redis answer; Docker's healthcheck uses this.
     */
    get: operations["ready_ready_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * Access
     * @description How the current user relates to a preparation.
     * @enum {string}
     */
    Access: "owner" | "joined" | "public"
    /** CreatedOut */
    CreatedOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][]
    }
    /** InternalRatingIn */
    InternalRatingIn: {
      /**
       * Value
       * @enum {integer}
       */
      value: -1 | 1
      /** User Id */
      user_id: string
    }
    /** InternalReportIn */
    InternalReportIn: {
      reason: components["schemas"]["ReportReason"]
      /**
       * Comment
       * @default
       */
      comment: string
      /** User Id */
      user_id: string
    }
    /** MyPreparation */
    MyPreparation: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Title */
      title: string
      /** Level */
      level: string
      /** Visibility */
      visibility: string
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Topic Count */
      topic_count: number
      /** Rating Avg */
      rating_avg: number | null
      /** Rating Count */
      rating_count: number
      /** Join Count */
      join_count: number
      /** Owned */
      owned: boolean
      /** Done */
      done: boolean
    }
    /** MyReportOut */
    MyReportOut: {
      /** Reported */
      reported: boolean
    }
    /** OptionIn */
    OptionIn: {
      /** Answer */
      answer: string
      /** Correct */
      correct: boolean
    }
    /** PreparationDetail */
    PreparationDetail: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Title */
      title: string
      /** Level */
      level: string
      /** Visibility */
      visibility: string
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Topic Count */
      topic_count: number
      /** Rating Avg */
      rating_avg: number | null
      /** Rating Count */
      rating_count: number
      /** Join Count */
      join_count: number
      /** Requirements */
      requirements: string[]
      /** Topics */
      topics: components["schemas"]["TopicOut"][]
      access: components["schemas"]["Access"]
      /** My Rating */
      my_rating: number | null
      /** Done */
      done: boolean
      /** Rating Scale */
      rating_scale: number
    }
    /**
     * PreparationIn
     * @description A generated preparation or interview, as generation saves it in library.
     */
    PreparationIn: {
      /**
       * Generation Id
       * Format: uuid
       */
      generation_id: string
      /** Owner Uid */
      owner_uid: string
      /** Source Text */
      source_text: string
      /** Title */
      title: string
      /** Level */
      level: string
      /** Requirements */
      requirements: string[]
      /** Topics */
      topics: components["schemas"]["TopicIn"][]
    }
    /** PreparationRatingIn */
    PreparationRatingIn: {
      /** Value */
      value: number
    }
    /** PreparationSummary */
    PreparationSummary: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Title */
      title: string
      /** Level */
      level: string
      /** Visibility */
      visibility: string
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Topic Count */
      topic_count: number
      /** Rating Avg */
      rating_avg: number | null
      /** Rating Count */
      rating_count: number
      /** Join Count */
      join_count: number
    }
    /**
     * PushBody
     * @description What Pub/Sub sends to a push endpoint.
     */
    PushBody: {
      message: components["schemas"]["PushMessage"]
      /** Subscription */
      subscription: string
    }
    /** PushMessage */
    PushMessage: {
      /**
       * Data
       * @default
       */
      data: string
      /**
       * Attributes
       * @default {}
       */
      attributes: {
        [key: string]: string
      }
      /** Messageid */
      messageId: string
    }
    /**
     * QuestionContext
     * @description What the generator needs to replace a question without repeating its topic.
     */
    QuestionContext: {
      /**
       * Set Id
       * Format: uuid
       */
      set_id: string
      /** Kind */
      kind: string
      /** Owner Id */
      owner_id: string
      /** Level */
      level: string
      /** Topic */
      topic: string
      /** Subtopics */
      subtopics: string[]
      /** Existing */
      existing: string[]
    }
    /** QuestionIn */
    QuestionIn: {
      /** Text */
      text: string
      /** Options */
      options: components["schemas"]["OptionIn"][]
    }
    /** QuestionOut */
    QuestionOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Text */
      text: string
      /** Options */
      options: components["schemas"]["OptionIn"][]
    }
    /**
     * QuestionQuality
     * @description What the verifier looks at: the question, how it's answered and what users reported.
     */
    QuestionQuality: {
      /** Text */
      text: string
      /** Options */
      options: components["schemas"]["OptionIn"][]
      /** Answers */
      answers: number
      /** Option Picks */
      option_picks: {
        [key: string]: number
      }
      /** Reports */
      reports: components["schemas"]["ReportNote"][]
    }
    /** QuestionRatingIn */
    QuestionRatingIn: {
      /**
       * Value
       * @enum {integer}
       */
      value: -1 | 1
    }
    /** QuestionRatingOut */
    QuestionRatingOut: {
      /** Value */
      value?: (-1 | 1) | null
    }
    /** QuestionReplace */
    QuestionReplace: {
      /** Text */
      text: string
      /** Options */
      options: components["schemas"]["OptionIn"][]
    }
    /** QuestionText */
    QuestionText: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Text */
      text: string
      /**
       * Likes
       * @default 0
       */
      likes: number
      /**
       * Dislikes
       * @default 0
       */
      dislikes: number
      /**
       * Reports
       * @default 0
       */
      reports: number
    }
    /** ReportIn */
    ReportIn: {
      reason: components["schemas"]["ReportReason"]
      /**
       * Comment
       * @default
       */
      comment: string
    }
    /** ReportNote */
    ReportNote: {
      /** Reason */
      reason: string
      /** Comment */
      comment: string
    }
    /**
     * ReportOut
     * @description A report without the reporter's identity.
     */
    ReportOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Reason */
      reason: string
      /** Comment */
      comment: string
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
    }
    /**
     * ReportReason
     * @enum {string}
     */
    ReportReason: "wrong_answer" | "unclear" | "off_topic" | "other"
    /** ReuseIn */
    ReuseIn: {
      /** Embedding */
      embedding: number[]
      /** Level */
      level: string
      /** Count */
      count: number
    }
    /** ReusedQuestion */
    ReusedQuestion: {
      /** Text */
      text: string
      /** Options */
      options: components["schemas"]["OptionIn"][]
    }
    /**
     * SetContent
     * @description Internal: every question of an interview, with answers.
     */
    SetContent: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Title */
      title: string
      /** Topics */
      topics: components["schemas"]["SetTopicOut"][]
    }
    /** SetOut */
    SetOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Kind */
      kind: string
      /** Owner Id */
      owner_id: string
      /** Title */
      title: string
      /** Level */
      level: string
      /** Topics */
      topics: components["schemas"]["TopicOut"][]
    }
    /** SetTopicOut */
    SetTopicOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Title */
      title: string
      /** Questions */
      questions: components["schemas"]["QuestionOut"][]
    }
    /** ShareIn */
    ShareIn: {
      /**
       * Email
       * Format: email
       */
      email: string
    }
    /**
     * ShareInviteOut
     * @description What the invited person sees before accepting.
     */
    ShareInviteOut: {
      /**
       * Preparation Id
       * Format: uuid
       */
      preparation_id: string
      /** Title */
      title: string
      /** Email */
      email: string
      /** Accepted */
      accepted: boolean
    }
    /** ShareOut */
    ShareOut: {
      /** Email */
      email: string
      /** Accepted */
      accepted: boolean
      /**
       * Undelivered
       * @default false
       */
      undelivered: boolean
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
    }
    /** TitleIn */
    TitleIn: {
      /** Title */
      title: string
    }
    /** TopicEmbedding */
    TopicEmbedding: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Embedding */
      embedding: number[]
    }
    /** TopicIn */
    TopicIn: {
      /** Title */
      title: string
      /** Subtopics */
      subtopics: string[]
      /** Questions */
      questions: components["schemas"]["QuestionIn"][]
      /** Embedding */
      embedding?: number[] | null
    }
    /** TopicOut */
    TopicOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Title */
      title: string
      /** Subtopics */
      subtopics: string[]
      /** Question Count */
      question_count: number
    }
    /**
     * TopicQuestionsOut
     * @description Internal only: a topic with its questions' correct flags.
     */
    TopicQuestionsOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /**
       * Preparation Id
       * Format: uuid
       */
      preparation_id: string
      /** Title */
      title: string
      /** Questions */
      questions: components["schemas"]["QuestionOut"][]
    }
    /** TopicToEmbed */
    TopicToEmbed: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Title */
      title: string
      /** Subtopics */
      subtopics: string[]
    }
    /** User */
    User: {
      /** Uid */
      uid: string
      /** Email */
      email: string
      /** Email Verified */
      email_verified: boolean
      /** Name */
      name?: string | null
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
      /** Input */
      input?: unknown
      /** Context */
      ctx?: Record<string, never>
    }
    /**
     * Visibility
     * @enum {string}
     */
    Visibility: "private" | "public"
    /** VisibilityIn */
    VisibilityIn: {
      visibility: components["schemas"]["Visibility"]
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  me_me_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["User"]
        }
      }
    }
  }
  delete_me_me_delete: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  export_me_me_export_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            [key: string]: unknown
          }
        }
      }
    }
  }
  list_mine_preparations_get: {
    parameters: {
      query?: {
        offset?: number
        limit?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["MyPreparation"][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  list_topic_questions_preparations_topics__topic_id__questions_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        topic_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["QuestionText"][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_preparation_preparations__preparation_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        preparation_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["PreparationDetail"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  delete_preparation_preparations__preparation_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        preparation_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  update_visibility_preparations__preparation_id__patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        preparation_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["VisibilityIn"]
      }
    }
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  update_title_preparations__preparation_id__title_patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        preparation_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["TitleIn"]
      }
    }
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  join_preparations__preparation_id__join_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        preparation_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  leave_preparations__preparation_id__join_delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        preparation_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  rate_preparations__preparation_id__rating_put: {
    parameters: {
      query?: never
      header?: never
      path: {
        preparation_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["PreparationRatingIn"]
      }
    }
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  list_shares_preparations__preparation_id__shares_get: {
    parameters: {
      query?: {
        offset?: number
        limit?: number
      }
      header?: never
      path: {
        preparation_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ShareOut"][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  share_preparations__preparation_id__shares_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        preparation_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["ShareIn"]
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ShareOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_share_shares__token__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        token: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ShareInviteOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  accept_share_shares__token__accept_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        token: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  regenerate_questions__question_id__regenerate_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        question_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            [key: string]: unknown
          }
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_rating_questions__question_id__rating_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        question_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["QuestionRatingOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  rate_questions__question_id__rating_put: {
    parameters: {
      query?: never
      header?: never
      path: {
        question_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["QuestionRatingIn"]
      }
    }
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  list_reports_questions__question_id__reports_get: {
    parameters: {
      query?: {
        offset?: number
        limit?: number
      }
      header?: never
      path: {
        question_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ReportOut"][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  report_questions__question_id__reports_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        question_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReportIn"]
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  my_report_questions__question_id__reports_mine_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        question_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["MyReportOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  search_library_library_get: {
    parameters: {
      query?: {
        q?: string
        offset?: number
        limit?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["PreparationSummary"][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  create_preparation_internal_preparations_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["PreparationIn"]
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["CreatedOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  create_interview_internal_interviews_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["PreparationIn"]
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["CreatedOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  delete_interview_internal_interviews__set_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        set_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  rename_set_internal_sets__set_id__title_patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        set_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["TitleIn"]
      }
    }
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_set_internal_sets__set_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        set_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["SetOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_set_content_internal_sets__set_id__content_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        set_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["SetContent"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  list_question_texts_internal_sets__set_id__question_texts_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        set_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            [key: string]: string
          }
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  list_topic_questions_internal_sets__set_id__topics__topic_id__questions_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        set_id: string
        topic_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["QuestionText"][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  list_question_reports_internal_sets__set_id__questions__question_id__reports_get: {
    parameters: {
      query?: {
        offset?: number
        limit?: number
      }
      header?: never
      path: {
        set_id: string
        question_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ReportOut"][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_question_context_internal_questions__question_id__context_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        question_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["QuestionContext"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  replace_question_internal_questions__question_id__put: {
    parameters: {
      query?: never
      header?: never
      path: {
        question_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["QuestionReplace"]
      }
    }
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_topic_questions_internal_topics__topic_id__get: {
    parameters: {
      query: {
        user_id: string
      }
      header?: never
      path: {
        topic_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["TopicQuestionsOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  flush_outbox_internal_schedules_outbox_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  receive_event_internal_events_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["PushBody"]
      }
    }
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_rating_internal_questions__question_id__rating_get: {
    parameters: {
      query: {
        user_id: string
      }
      header?: never
      path: {
        question_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["QuestionRatingOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  rate_internal_questions__question_id__rating_put: {
    parameters: {
      query?: never
      header?: never
      path: {
        question_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["InternalRatingIn"]
      }
    }
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  my_report_internal_questions__question_id__reports_mine_get: {
    parameters: {
      query: {
        user_id: string
      }
      header?: never
      path: {
        question_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["MyReportOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  report_internal_questions__question_id__reports_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        question_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["InternalReportIn"]
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_quality_internal_questions__question_id__quality_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        question_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["QuestionQuality"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  keep_internal_questions__question_id__keep_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        question_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  find_reusable_internal_reuse_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReuseIn"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ReusedQuestion"][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  list_missing_embeddings_internal_embeddings_missing_get: {
    parameters: {
      query?: {
        limit?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["TopicToEmbed"][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  save_embeddings_internal_embeddings_put: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["TopicEmbedding"][]
      }
    }
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  share_undelivered_internal_shares__share_id__undelivered_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        share_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  health_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            [key: string]: unknown
          }
        }
      }
    }
  }
  ready_ready_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            [key: string]: unknown
          }
        }
      }
    }
  }
}
