/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/me": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Feed
     * @description The bell: the latest notifications, the user's own and their companies', and how many
     *     came since they last opened it.
     */
    get: operations["get_feed_me_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/me/seen": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Mark Seen
     * @description Opening the bell: everything so far counts as read.
     */
    post: operations["mark_seen_me_seen_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/me/stream": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Stream
     * @description Server-sent events while a tab is open: {"new": true} as soon as a notification comes,
     *     so the bell reloads; heartbeat comments in between.
     */
    get: operations["stream_me_stream_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/events": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Receive Event
     * @description Pub/Sub pushes every event here. A failed email answers with an error, so Pub/Sub
     *     retries it, and moves it to the dead-letter topic after the subscription's maximum
     *     attempts; Resend never sends the same message twice.
     */
    post: operations["receive_event_internal_events_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/webhooks/resend": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Resend Webhook
     * @description Resend retries until it gets a 2xx, and marking an invite is idempotent, so a failed
     *     call to its owner simply comes back later.
     */
    post: operations["resend_webhook_webhooks_resend_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/users/{user_id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Delete User
     * @description Library, deleting an account: the user's own notifications go; their companies' stay
     *     with the companies.
     */
    delete: operations["delete_user_internal_users__user_id__delete"]
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/users/{user_id}/export": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Export User
     * @description Library, for "Download my data": the user's own notifications.
     */
    get: operations["export_user_internal_users__user_id__export_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/health": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Health */
    get: operations["health_health_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/ready": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Ready
     * @description Ready once the database answers; Docker's healthcheck and the startup probe use this. Redis
     *     isn't checked: an outage there shouldn't stop the service from starting.
     */
    get: operations["ready_ready_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** FeedOut */
    FeedOut: {
      /** Items */
      items: components["schemas"]["NotificationOut"][]
      /** Unread */
      unread: number
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][]
    }
    /**
     * NotificationOut
     * @description What the bell shows: `kind` picks the text, `data` fills it, `link` opens the page.
     */
    NotificationOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Kind */
      kind: string
      /** Link */
      link: string
      /** Data */
      data: {
        [key: string]: unknown
      }
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
    }
    /**
     * PushBody
     * @description What Pub/Sub sends to a push endpoint.
     */
    PushBody: {
      message: components["schemas"]["PushMessage"]
      /** Subscription */
      subscription: string
    }
    /** PushMessage */
    PushMessage: {
      /**
       * Data
       * @default
       */
      data: string
      /**
       * Attributes
       * @default {}
       */
      attributes: {
        [key: string]: string
      }
      /** Messageid */
      messageId: string
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
      /** Input */
      input?: unknown
      /** Context */
      ctx?: Record<string, never>
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  get_feed_me_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["FeedOut"]
        }
      }
    }
  }
  mark_seen_me_seen_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  stream_me_stream_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": unknown
        }
      }
    }
  }
  receive_event_internal_events_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["PushBody"]
      }
    }
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  resend_webhook_webhooks_resend_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  delete_user_internal_users__user_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        user_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  export_user_internal_users__user_id__export_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        user_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            [key: string]: unknown
          }
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  health_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            [key: string]: unknown
          }
        }
      }
    }
  }
  ready_ready_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            [key: string]: unknown
          }
        }
      }
    }
  }
}
