/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/me": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Feed
     * @description The bell: the latest notifications, the user's own and their companies', and how many
     *     came since they last opened it.
     */
    get: operations["get_feed_me_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/me/seen": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Mark Seen
     * @description Opening the bell: everything so far counts as read.
     */
    post: operations["mark_seen_me_seen_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/me/stream": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Stream
     * @description Server-sent events while a tab is open: {"new": true} as soon as a notification comes,
     *     so the bell reloads; heartbeat comments in between.
     */
    get: operations["stream_me_stream_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/events": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Receive Event
     * @description Pub/Sub pushes every event here. A failed email or Slack post answers with an error, so
     *     Pub/Sub retries it, and moves it to the dead-letter topic after the subscription's maximum
     *     attempts; neither Resend nor Slack gets the same message twice. Over Resend's per-second limit
     *     (a burst of invites) it answers 429: Pub/Sub retries with backoff, and it isn't counted as a
     *     server error.
     */
    post: operations["receive_event_internal_events_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/webhooks/resend": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Resend Webhook
     * @description Resend retries until it gets a 2xx, and marking an invite is idempotent, so a failed
     *     call to its owner simply comes back later.
     */
    post: operations["resend_webhook_webhooks_resend_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/users/{user_id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Delete User
     * @description Library, deleting an account: the user's own notifications go, and companies'
     *     notifications about them as a candidate (their email and grade); the Slack channels they
     *     connected stay with their companies, without their id. The log of digests and reminders
     *     sent to them goes too.
     */
    delete: operations["delete_user_internal_users__user_id__delete"]
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/users/{user_id}/export": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Export User
     * @description Library, for "Download my data": the user's own notifications and the Slack channels
     *     they connected.
     */
    post: operations["export_user_internal_users__user_id__export_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/slack": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Slack
     * @description The company's Slack channel and the notifications it gets; every member sees it.
     */
    get: operations["get_slack_slack_get"]
    put?: never
    post?: never
    /** Disconnect */
    delete: operations["disconnect_slack_delete"]
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/slack/start": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Start
     * @description Where "Add to Slack" goes: Slack's page to approve prepza and pick a channel.
     */
    get: operations["start_slack_start_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/slack/callback": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Callback
     * @description Slack sends the browser back here; the signed, one-time state says whose company it is.
     *     Then on to the company's Slack page.
     */
    get: operations["callback_slack_callback_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/slack/kinds": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /** Set Kinds */
    put: operations["set_kinds_slack_kinds_put"]
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/unsubscribe/{token}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Describe
     * @description What an email's unsubscribe link stops; no sign-in. Reading it changes nothing, as mail
     *     scanners open links.
     */
    get: operations["describe_unsubscribe__token__get"]
    put?: never
    /**
     * Unsubscribe
     * @description Applies the link; no sign-in. The unsubscribe page's button posts here, and so do mail
     *     clients' own unsubscribe buttons (RFC 8058: `List-Unsubscribe=One-Click` as the body, which
     *     needs nothing more). Safe to repeat.
     */
    post: operations["unsubscribe_unsubscribe__token__post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/superadmin/candidate-opt-outs/lookup": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Look Up
     * @description The companies that invited the address or whose emails it stopped, by name.
     */
    post: operations["look_up_superadmin_candidate_opt_outs_lookup_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/superadmin/candidate-opt-outs": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * Change
     * @description Stops a company's emails to the address (only a company that invited it), or lets them
     *     through again; answers with the companies as the lookup does.
     */
    put: operations["change_superadmin_candidate_opt_outs_put"]
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/schedules/digest": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Digest
     * @description Every 10 minutes for an hour each morning, from Cloud Scheduler: the activity digest. Each
     *     run goes on where the last one stopped; nobody gets it twice in a day.
     */
    post: operations["digest_internal_schedules_digest_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/schedules/reminders": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Reminders
     * @description Every 10 minutes for an hour each morning, from Cloud Scheduler: reminders, each kind
     *     at most once a week to a user. The sent log's old rows go too.
     */
    post: operations["reminders_internal_schedules_reminders_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/health": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Health */
    get: operations["health_health_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/ready": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Ready
     * @description Ready once the database answers; Docker's healthcheck and the startup probe use this. Redis
     *     isn't checked: an outage there shouldn't stop the service from starting.
     */
    get: operations["ready_ready_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * CandidateOptOutIn
     * @description A superadmin stops a company's emails to the address, or lets them through again.
     */
    CandidateOptOutIn: {
      /** Email */
      email: string
      /** Company Id */
      company_id: string
      /** Stopped */
      stopped: boolean
    }
    /** CandidateOptOutsOut */
    CandidateOptOutsOut: {
      /** Companies */
      companies: components["schemas"]["CompanyOptOutOut"][]
    }
    /**
     * CompanyOptOutOut
     * @description A company that invited an address, or whose emails it stopped: whether every email from
     *     the company to it is stopped, and for how many invites only the reminders are.
     */
    CompanyOptOutOut: {
      /** Company Id */
      company_id: string
      /** Name */
      name: string
      /** Stopped */
      stopped: boolean
      /** Stopped Reminders */
      stopped_reminders: number
    }
    /** FeedOut */
    FeedOut: {
      /** Items */
      items: components["schemas"]["NotificationOut"][]
      /** Unread */
      unread: number
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][]
    }
    /**
     * NotificationOut
     * @description What the bell shows: `kind` picks the text, `data` fills it, `link` opens the page.
     */
    NotificationOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Kind */
      kind: string
      /** Link */
      link: string
      /** Data */
      data: {
        [key: string]: unknown
      }
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
    }
    /**
     * PushBody
     * @description What Pub/Sub sends to a push endpoint.
     */
    PushBody: {
      message: components["schemas"]["PushMessage"]
      /** Subscription */
      subscription: string
    }
    /** PushMessage */
    PushMessage: {
      /**
       * Data
       * @default
       */
      data: string
      /**
       * Attributes
       * @default {}
       */
      attributes: {
        [key: string]: string
      }
      /** Messageid */
      messageId: string
    }
    /** SlackKindsIn */
    SlackKindsIn: {
      /** Kinds */
      kinds: string[]
    }
    /**
     * SlackOut
     * @description The company's Slack channel as the page shows it: never its web hook.
     */
    SlackOut: {
      /** Connected */
      connected: boolean
      /** Status */
      status?: string | null
      /** Team */
      team?: string | null
      /** Channel */
      channel?: string | null
      /** Kinds */
      kinds: string[]
      /** All Kinds */
      all_kinds: string[]
    }
    /** SlackStartOut */
    SlackStartOut: {
      /** Url */
      url: string
    }
    /**
     * UnsubscribeOut
     * @description What a link stops, for the page to say before it's confirmed: the type, and for a
     *     candidate's link the company's name.
     */
    UnsubscribeOut: {
      type: components["schemas"]["UnsubscribeType"]
      /** Company */
      company?: string | null
    }
    /**
     * UnsubscribeType
     * @description What an unsubscribe link stops. A user's optional emails: one kind of the activity digest,
     *     the whole digest, reminders, product updates or offers. A candidate's emails, sent on a
     *     company's behalf: the reminders for one invite, or every email from that company.
     * @enum {string}
     */
    UnsubscribeType:
      | "candidate_finished"
      | "invite_undelivered"
      | "ats_not_invited"
      | "interview_ready"
      | "digest"
      | "reminders"
      | "updates"
      | "promotions"
      | "invite_reminders"
      | "company"
    /**
     * UserEmailIn
     * @description An email address sent in the body, so request logs don't record it: the account's, in
     *     library's calls to delete or export a user's data, or the one a superadmin looks up.
     */
    UserEmailIn: {
      /** Email */
      email: string
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
      /** Input */
      input?: unknown
      /** Context */
      ctx?: Record<string, never>
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  get_feed_me_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["FeedOut"]
        }
      }
    }
  }
  mark_seen_me_seen_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  stream_me_stream_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": unknown
        }
      }
    }
  }
  receive_event_internal_events_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["PushBody"]
      }
    }
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  resend_webhook_webhooks_resend_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  delete_user_internal_users__user_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        user_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserEmailIn"]
      }
    }
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  export_user_internal_users__user_id__export_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        user_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            [key: string]: unknown
          }
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_slack_slack_get: {
    parameters: {
      query: {
        company_id: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["SlackOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  disconnect_slack_delete: {
    parameters: {
      query: {
        company_id: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  start_slack_start_get: {
    parameters: {
      query: {
        company_id: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["SlackStartOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  callback_slack_callback_get: {
    parameters: {
      query: {
        state: string
        code?: string | null
        error?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  set_kinds_slack_kinds_put: {
    parameters: {
      query: {
        company_id: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["SlackKindsIn"]
      }
    }
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  describe_unsubscribe__token__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        token: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["UnsubscribeOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  unsubscribe_unsubscribe__token__post: {
    parameters: {
      query?: never
      header?: never
      path: {
        token: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  look_up_superadmin_candidate_opt_outs_lookup_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserEmailIn"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["CandidateOptOutsOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  change_superadmin_candidate_opt_outs_put: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["CandidateOptOutIn"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["CandidateOptOutsOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  digest_internal_schedules_digest_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  reminders_internal_schedules_reminders_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  health_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            [key: string]: unknown
          }
        }
      }
    }
  }
  ready_ready_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            [key: string]: unknown
          }
        }
      }
    }
  }
}
