/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/sessions/{session_id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Session */
    get: operations["get_session_sessions__session_id__get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/sessions/{session_id}/topics": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Topics
     * @description Every topic of this candidate's interview, so they can open the ones besides the first.
     */
    get: operations["list_topics_sessions__session_id__topics_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/sessions/{session_id}/next": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Next Question */
    get: operations["get_next_question_sessions__session_id__next_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/sessions/{session_id}/signals": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Add Signal
     * @description The candidate's browser reports leaving the page or copying, saved with the question on
     *     screen so the scorecard can show where it happened.
     */
    post: operations["add_signal_sessions__session_id__signals_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/sessions/{session_id}/answers": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Answer Question */
    post: operations["answer_question_sessions__session_id__answers_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/sessions/{session_id}/review": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Review Session
     * @description Once a section is finished, candidates see the questions they answered and their picks,
     *     never whether they were right or the key. Never while it runs: that would show questions
     *     before their clock starts.
     */
    get: operations["review_session_sessions__session_id__review_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/sessions/{session_id}/finish": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Finish */
    post: operations["finish_sessions__session_id__finish_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/sessions/{session_id}/step": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Next Step
     * @description Opens the candidate's interview, or moves it on after an answer or a time-out: the
     *     server decides which section and question come next, and when the interview is done.
     */
    post: operations["next_step_sessions__session_id__step_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/sessions/{session_id}/finish-interview": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Finish Interview */
    post: operations["finish_interview_sessions__session_id__finish_interview_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/practice/{template_id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Start Practice */
    post: operations["start_practice_practice__template_id__post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/practice/{template_id}/size": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Practice Size
     * @description Public, for the test's page: how many questions a round has, kept for a few minutes.
     */
    get: operations["practice_size_practice__template_id__size_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/practice/rounds/{round_id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Round
     * @description The talent's own round only.
     */
    get: operations["get_round_practice_rounds__round_id__get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/practice/{template_id}/rounds": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Rounds
     * @description The talent's rounds on the template, newest first, to see their progress.
     */
    get: operations["list_rounds_practice__template_id__rounds_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/practice/{template_id}/progress": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Topic Progress Route
     * @description How far the talent got on each of the template's topics in their latest round.
     */
    get: operations["topic_progress_route_practice__template_id__progress_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/sessions/{session_id}/questions/{question_id}/rating": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Rating */
    get: operations["get_rating_sessions__session_id__questions__question_id__rating_get"]
    /** Rate */
    put: operations["rate_sessions__session_id__questions__question_id__rating_put"]
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/sessions/{session_id}/questions/{question_id}/reports/mine": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** My Report */
    get: operations["my_report_sessions__session_id__questions__question_id__reports_mine_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/sessions/{session_id}/questions/{question_id}/reports": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Report */
    post: operations["report_sessions__session_id__questions__question_id__reports_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/help/faq": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Faq
     * @description The FAQ in the page's language, with today's prices; public.
     */
    get: operations["get_faq_help_faq_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/help/legal/{document}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Legal
     * @description The terms or the privacy policy, in English only; public.
     */
    get: operations["get_legal_help_legal__document__get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/help/chat": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Help Chat
     * @description Answers questions about prepza, for visitors too. Streams server-sent events:
     *     {"delta"}..., then {"done"} or {"error"}. Refused during the emergency pause, as it's AI.
     */
    post: operations["help_chat_help_chat_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/help/contact": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Contact
     * @description The contact page's message; notifications emails it to prepza's inbox. Public.
     */
    post: operations["contact_help_contact_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/sessions": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Create Sessions
     * @description Creates one session per topic for a candidate invite; returns existing ones if any.
     */
    post: operations["create_sessions_internal_sessions_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/invite-scores": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Invite Scores */
    post: operations["invite_scores_internal_invite_scores_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/answer-counts": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Interview Answer Counts
     * @description For the superadmin's pass rates: each interview's answers, [timed out, all].
     */
    post: operations["interview_answer_counts_internal_answer_counts_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/interviews/{interview_set_id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Delete Interview Data
     * @description Called by companies before it deletes an interview; safe to repeat.
     */
    delete: operations["delete_interview_data_internal_interviews__interview_set_id__delete"]
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/invites/{invite_id}/scorecard": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Invite Scorecard */
    get: operations["invite_scorecard_internal_invites__invite_id__scorecard_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/questions/{question_id}/rescore": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Rescore Question
     * @description The question's answer key was corrected: candidates who answered it are marked again.
     */
    post: operations["rescore_question_internal_questions__question_id__rescore_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/schedules/outbox": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Flush Outbox
     * @description Every minute, from Cloud Scheduler: publishes events that weren't published right after
     *     their change.
     */
    post: operations["flush_outbox_internal_schedules_outbox_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/schedules/expire-interviews": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Expire Interviews
     * @description Every minute, from Cloud Scheduler: finishes interviews whose time ran out after the
     *     candidate left, so companies see them as finished.
     */
    post: operations["expire_interviews_internal_schedules_expire_interviews_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/superadmin/stats": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Stats
     * @description Practice rounds, all time or in one month, for the stats
     *     tab.
     */
    get: operations["get_stats_superadmin_stats_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/users/{user_id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Delete User
     * @description Part of deleting an account (library coordinates it); safe to repeat.
     */
    delete: operations["delete_user_internal_users__user_id__delete"]
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/users/{user_id}/export": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Export User */
    get: operations["export_user_internal_users__user_id__export_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/invites/delete": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Delete Invite Sessions
     * @description Companies' retention: candidates' sessions go with their expired invites.
     */
    post: operations["delete_invite_sessions_internal_invites_delete_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/internal/maintenance/running": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Running Interviews
     * @description For companies' maintenance switch: the candidates who may lose time if it's turned on.
     */
    get: operations["running_interviews_internal_maintenance_running_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/health": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Health */
    get: operations["health_health_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/ready": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Ready
     * @description Ready once the database answers; Docker's healthcheck and the startup probe use this. Redis
     *     isn't checked: an outage there shouldn't stop the service from starting.
     */
    get: operations["ready_ready_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** AnswerCreate */
    AnswerCreate: {
      /**
       * Question Id
       * Format: uuid
       */
      question_id: string
      /** Option Index */
      option_index: number
    }
    /** AnswerView */
    AnswerView: {
      /**
       * Answer Id
       * Format: uuid
       */
      answer_id: string
      /** Option Index */
      option_index: number | null
      /** Correct */
      correct: boolean | null
      /** Seconds */
      seconds?: number | null
      /**
       * Fast
       * @default false
       */
      fast: boolean
    }
    /** ContactRequest */
    ContactRequest: {
      /** Name */
      name: string
      /**
       * Email
       * Format: email
       */
      email: string
      /** Message */
      message: string
    }
    /** FaqItemOut */
    FaqItemOut: {
      /** Key */
      key: string
      /** Question */
      question: string
      /** Answer */
      answer: string
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][]
    }
    /**
     * HelpChatRequest
     * @description The conversation so far, ending with the new question; the page keeps it.
     */
    HelpChatRequest: {
      /** Messages */
      messages: components["schemas"]["HelpMessage"][]
    }
    /** HelpMessage */
    HelpMessage: {
      role: components["schemas"]["HelpRole"]
      /** Content */
      content: string
    }
    /**
     * HelpRole
     * @enum {string}
     */
    HelpRole: "user" | "assistant"
    /**
     * IntegritySignal
     * @description What the candidate's browser reports during an interview.
     * @enum {string}
     */
    IntegritySignal: "tab_leave" | "copy"
    /**
     * InterviewStep
     * @description Where a candidate's interview stands: the section on screen and its waiting question,
     *     every section, and whether the whole interview is finished.
     */
    InterviewStep: {
      session: components["schemas"]["SessionOut"]
      question: components["schemas"]["NextQuestion"] | null
      /** Topics */
      topics: components["schemas"]["SessionTopicOut"][]
      /** Done */
      done: boolean
    }
    /** InviteIdsIn */
    InviteIdsIn: {
      /** Invite Ids */
      invite_ids: string[]
    }
    /** InviteScoresIn */
    InviteScoresIn: {
      /** Invite Ids */
      invite_ids: string[]
    }
    /**
     * LegalDocument
     * @enum {string}
     */
    LegalDocument: "terms" | "privacy" | "dpa"
    /** LegalOut */
    LegalOut: {
      /** Intro */
      intro: string
      /** Updated */
      updated: string
      /** Sections */
      sections: components["schemas"]["LegalSectionOut"][]
    }
    /** LegalSectionOut */
    LegalSectionOut: {
      /** Heading */
      heading: string
      /**
       * Paragraphs
       * @default []
       */
      paragraphs: string[]
      /**
       * Items
       * @default []
       */
      items: string[]
    }
    /**
     * NextQuestion
     * @description The next unanswered question, without the correct flags.
     */
    NextQuestion: {
      /**
       * Question Id
       * Format: uuid
       */
      question_id: string
      /** Number */
      number: number
      /** Text */
      text: string
      /** Options */
      options: string[]
      /** Seconds Left */
      seconds_left?: number | null
    }
    /** Option */
    Option: {
      /** Answer */
      answer: string
      /** Correct */
      correct: boolean
    }
    /**
     * PracticeRoundOut
     * @description A talent's round, with every question's right answer once it's finished.
     */
    PracticeRoundOut: {
      /**
       * Round Id
       * Format: uuid
       */
      round_id: string
      /**
       * Template Id
       * Format: uuid
       */
      template_id: string
      /** Title */
      title: string | null
      /** Finished */
      finished: boolean
      /** Grade */
      grade: number | null
      /** Answered */
      answered: number
      /** Total */
      total: number
      /**
       * Started At
       * Format: date-time
       */
      started_at: string
      /** Open Session Id */
      open_session_id: string | null
      /** Topics */
      topics: components["schemas"]["PracticeTopicResult"][]
    }
    /** PracticeRoundSummary */
    PracticeRoundSummary: {
      /**
       * Round Id
       * Format: uuid
       */
      round_id: string
      /**
       * Started At
       * Format: date-time
       */
      started_at: string
      /** Finished */
      finished: boolean
      /** Progress */
      progress: number
      /** Grade */
      grade: number | null
    }
    /**
     * PracticeSizeOut
     * @description How many questions a practice round on the template has.
     */
    PracticeSizeOut: {
      /** Questions */
      questions: number
    }
    /**
     * PracticeStartOut
     * @description A new practice round: its id, and the first section to open.
     */
    PracticeStartOut: {
      /**
       * Round Id
       * Format: uuid
       */
      round_id: string
      /**
       * Session Id
       * Format: uuid
       */
      session_id: string
    }
    /**
     * PracticeTopicProgress
     * @description How far the talent got on one of the template's topics in their latest round.
     */
    PracticeTopicProgress: {
      /**
       * Topic Id
       * Format: uuid
       */
      topic_id: string
      /** Answered */
      answered: number
      /** Total */
      total: number
    }
    /** PracticeTopicResult */
    PracticeTopicResult: {
      /**
       * Session Id
       * Format: uuid
       */
      session_id: string
      /** Title */
      title: string
      /** Score */
      score: number | null
      /** Review */
      review: components["schemas"]["ReviewItem"][]
    }
    /** Question */
    Question: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Text */
      text: string
      /** Options */
      options: components["schemas"]["Option"][]
    }
    /** RatingIn */
    RatingIn: {
      /**
       * Value
       * @enum {integer}
       */
      value: -1 | 1
    }
    /** ReportIn */
    ReportIn: {
      /** Reason */
      reason: string
      /**
       * Comment
       * @default
       */
      comment: string
    }
    /**
     * RescoreIn
     * @description A question's corrected content: its text and options with the right one marked, and the
     *     interview it belongs to (left out by older callers: every session is looked at).
     */
    RescoreIn: {
      /** Text */
      text: string
      /** Options */
      options: {
        [key: string]: unknown
      }[]
      /** Set Id */
      set_id?: string | null
    }
    /**
     * ReviewItem
     * @description One question of a round. The correct option only once it's answered.
     */
    ReviewItem: {
      /**
       * Question Id
       * Format: uuid
       */
      question_id: string
      /** Number */
      number: number
      /** Text */
      text: string
      /** Options */
      options: string[]
      /** Correct Option Index */
      correct_option_index: number | null
      answer: components["schemas"]["AnswerView"] | null
      /**
       * Tab Leaves
       * @default 0
       */
      tab_leaves: number
      /**
       * Copies
       * @default 0
       */
      copies: number
    }
    /**
     * RoundStatus
     * @enum {string}
     */
    RoundStatus: "in_progress" | "finished"
    /** RunningOut */
    RunningOut: {
      /** Running */
      running: number
    }
    /** ScorecardSession */
    ScorecardSession: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Topic Title */
      topic_title: string
      status: components["schemas"]["RoundStatus"]
      /** Final Score */
      final_score: number | null
      /** Tab Leaves */
      tab_leaves: number
      /** Copies */
      copies: number
      /** Fast Answers */
      fast_answers: number
      /** Review */
      review: components["schemas"]["ReviewItem"][]
    }
    /** SessionAnswerResult */
    SessionAnswerResult: {
      /**
       * Answer Id
       * Format: uuid
       */
      answer_id: string
      /** Answered */
      answered: number
      /** Total */
      total: number
    }
    /** SessionOut */
    SessionOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /**
       * Topic Id
       * Format: uuid
       */
      topic_id: string
      /**
       * Candidate Invite Id
       * Format: uuid
       */
      candidate_invite_id: string
      /** Topic Title */
      topic_title: string
      /** Interview Title */
      interview_title?: string | null
      /** Language */
      language?: string | null
      /**
       * Practice
       * @default false
       */
      practice: boolean
      status: components["schemas"]["RoundStatus"]
      /** Total */
      total: number
      /** Answered */
      answered: number
      /**
       * Started At
       * Format: date-time
       */
      started_at: string
      /** Finished At */
      finished_at: string | null
      /** Question Seconds */
      question_seconds: number | null
    }
    /** SessionTopicOut */
    SessionTopicOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Topic Title */
      topic_title: string
      status: components["schemas"]["RoundStatus"]
      /** Total */
      total: number
      /** Answered */
      answered: number
    }
    /** SessionsCreate */
    SessionsCreate: {
      /** User Id */
      user_id: string
      /**
       * Candidate Invite Id
       * Format: uuid
       */
      candidate_invite_id: string
      /** Topics */
      topics: components["schemas"]["TopicQuestions"][]
      /** Question Seconds */
      question_seconds: number
      /**
       * Preview
       * @default false
       */
      preview: boolean
    }
    /** SetIdsIn */
    SetIdsIn: {
      /** Set Ids */
      set_ids: string[]
    }
    /** SignalIn */
    SignalIn: {
      kind: components["schemas"]["IntegritySignal"]
    }
    /** StatsOut */
    StatsOut: {
      /** Counts */
      counts: {
        [key: string]: number
      }
      /** Currency */
      currency?: string | null
    }
    /** TopicQuestions */
    TopicQuestions: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /**
       * Preparation Id
       * Format: uuid
       */
      preparation_id: string
      /** Title */
      title: string
      /** Questions */
      questions: components["schemas"]["Question"][]
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
      /** Input */
      input?: unknown
      /** Context */
      ctx?: Record<string, never>
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  get_session_sessions__session_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        session_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["SessionOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  list_topics_sessions__session_id__topics_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        session_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["SessionTopicOut"][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_next_question_sessions__session_id__next_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        session_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["NextQuestion"] | null
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  add_signal_sessions__session_id__signals_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        session_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["SignalIn"]
      }
    }
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  answer_question_sessions__session_id__answers_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        session_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["AnswerCreate"]
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["SessionAnswerResult"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  review_session_sessions__session_id__review_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        session_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ReviewItem"][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  finish_sessions__session_id__finish_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        session_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["SessionOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  next_step_sessions__session_id__step_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        session_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["InterviewStep"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  finish_interview_sessions__session_id__finish_interview_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        session_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["InterviewStep"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  start_practice_practice__template_id__post: {
    parameters: {
      query?: never
      header?: never
      path: {
        template_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["PracticeStartOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  practice_size_practice__template_id__size_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        template_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["PracticeSizeOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_round_practice_rounds__round_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        round_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["PracticeRoundOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  list_rounds_practice__template_id__rounds_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        template_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["PracticeRoundSummary"][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  topic_progress_route_practice__template_id__progress_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        template_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["PracticeTopicProgress"][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_rating_sessions__session_id__questions__question_id__rating_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        session_id: string
        question_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  rate_sessions__session_id__questions__question_id__rating_put: {
    parameters: {
      query?: never
      header?: never
      path: {
        session_id: string
        question_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["RatingIn"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  my_report_sessions__session_id__questions__question_id__reports_mine_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        session_id: string
        question_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  report_sessions__session_id__questions__question_id__reports_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        session_id: string
        question_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReportIn"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_faq_help_faq_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["FaqItemOut"][]
        }
      }
    }
  }
  get_legal_help_legal__document__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        document: components["schemas"]["LegalDocument"]
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["LegalOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  help_chat_help_chat_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["HelpChatRequest"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  contact_help_contact_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["ContactRequest"]
      }
    }
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  create_sessions_internal_sessions_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["SessionsCreate"]
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["SessionOut"][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  invite_scores_internal_invite_scores_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["InviteScoresIn"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            [key: string]: {
              [key: string]: number | null
            }
          }
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  interview_answer_counts_internal_answer_counts_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["SetIdsIn"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            [key: string]: number[]
          }
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  delete_interview_data_internal_interviews__interview_set_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        interview_set_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  invite_scorecard_internal_invites__invite_id__scorecard_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        invite_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ScorecardSession"][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  rescore_question_internal_questions__question_id__rescore_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        question_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["RescoreIn"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            [key: string]: unknown
          }
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  flush_outbox_internal_schedules_outbox_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  expire_interviews_internal_schedules_expire_interviews_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  get_stats_superadmin_stats_get: {
    parameters: {
      query?: {
        month?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["StatsOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  delete_user_internal_users__user_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        user_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  export_user_internal_users__user_id__export_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        user_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            [key: string]: unknown
          }
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  delete_invite_sessions_internal_invites_delete_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["InviteIdsIn"]
      }
    }
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  running_interviews_internal_maintenance_running_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["RunningOut"]
        }
      }
    }
  }
  health_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            [key: string]: unknown
          }
        }
      }
    }
  }
  ready_ready_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            [key: string]: unknown
          }
        }
      }
    }
  }
}
