MAX_CONCURRENCY = 8
RECURSION_LIMIT = 200

MAX_TOPICS = 10
QUESTION_OVERSAMPLE = 1.2
ANSWER_BATCH_SIZE = 10
ANSWER_ATTEMPTS = 3
DISTRACTORS = 3
REGENERATE_ATTEMPTS = 3

MAX_GOAL_LENGTH = 20_000

JOB_TIMEOUT_SECONDS = 60 * 60
MAX_WORKER_JOBS = 4

GENERATION_FAILED = "Generation failed. Please try again."
