# Telling the pasted text's language (helpers/language.py), among LANGUAGES.

# A text is in a non-Latin script once this share of its letters is in it. Job descriptions in
# those carry many Latin tech terms (Python, PostgreSQL), so a majority would miss them; texts in
# Latin-script languages almost never contain those scripts.
SCRIPT_SHARE = 0.2

# Unicode ranges of each non-Latin script. Japanese mixes kana with Han characters, so both count
# as "cjk"; kana then tells Japanese from Chinese.
SCRIPTS = {
    "cyrillic": [(0x0400, 0x04FF)],
    "hebrew": [(0x0590, 0x05FF)],
    "arabic": [(0x0600, 0x06FF)],
    "devanagari": [(0x0900, 0x097F)],
    "thai": [(0x0E00, 0x0E7F)],
    "hangul": [(0x1100, 0x11FF), (0x3130, 0x318F), (0xAC00, 0xD7AF)],
    "cjk": [(0x3040, 0x30FF), (0x4E00, 0x9FFF)],
}
KANA = (0x3040, 0x30FF)
# The language each script means, where it means only one.
SCRIPT_LANGUAGES = {"hebrew": "he", "devanagari": "hi", "thai": "th", "hangul": "ko"}

# Persian's own letters (پ چ ژ گ, and its forms of ye and kaf); Arabic script without them is
# Arabic.
PERSIAN_LETTERS = set("پچژگیک")

# Letters only one of the two Cyrillic languages uses.
UKRAINIAN_LETTERS = set("іїєґ")
RUSSIAN_LETTERS = set("ыэъё")

# Common words of each Latin-script language, as they appear in job descriptions: the language
# with the most of them in a text is its language. Words shared by several languages count for
# each. A text with none of them is English, as short titles ("Python developer") usually are.
LATIN_WORDS = {
    "en": {
        "the",
        "and",
        "with",
        "for",
        "you",
        "will",
        "our",
        "are",
        "of",
        "to",
        "in",
        "we",
        "your",
        "experience",
        "team",
        "skills",
        "requirements",
        "role",
        "responsibilities",
        "knowledge",
        "years",
        "working",
    },
    "es": {
        "el",
        "los",
        "las",
        "del",
        "con",
        "para",
        "una",
        "que",
        "y",
        "experiencia",
        "equipo",
        "requisitos",
        "conocimientos",
        "buscamos",
        "trabajo",
        "nuestro",
        "años",
        "desarrollo",
    },
    "pt": {
        "os",
        "das",
        "dos",
        "com",
        "uma",
        "não",
        "você",
        "experiência",
        "equipe",
        "requisitos",
        "conhecimento",
        "vaga",
        "trabalho",
        "nosso",
        "anos",
        "desenvolvimento",
        "em",
    },
    "de": {
        "der",
        "die",
        "das",
        "und",
        "mit",
        "für",
        "wir",
        "sie",
        "ist",
        "erfahrung",
        "kenntnisse",
        "anforderungen",
        "aufgaben",
        "deine",
        "ihre",
        "bei",
        "von",
        "zu",
    },
    "fr": {
        "le",
        "la",
        "les",
        "des",
        "et",
        "avec",
        "pour",
        "vous",
        "nous",
        "une",
        "est",
        "expérience",
        "compétences",
        "équipe",
        "poste",
        "au",
        "du",
    },
    "it": {
        "il",
        "gli",
        "della",
        "delle",
        "con",
        "per",
        "una",
        "che",
        "di",
        "esperienza",
        "competenze",
        "requisiti",
        "lavoro",
        "nostro",
        "anni",
        "sviluppo",
    },
    "pl": {
        "i",
        "w",
        "z",
        "na",
        "do",
        "dla",
        "oraz",
        "jest",
        "się",
        "doświadczenie",
        "umiejętności",
        "wymagania",
        "zespół",
        "praca",
        "znajomość",
        "lat",
        "oferujemy",
    },
    "nl": {
        "de",
        "het",
        "een",
        "en",
        "van",
        "met",
        "voor",
        "wij",
        "je",
        "jij",
        "ervaring",
        "kennis",
        "vereisten",
        "werk",
        "onze",
        "bij",
    },
    "tr": {
        "ve",
        "ile",
        "için",
        "bir",
        "olan",
        "deneyim",
        "bilgi",
        "ekip",
        "gereksinimler",
        "iş",
        "yıl",
        "aranan",
        "nitelikler",
        "çalışma",
        "geliştirme",
    },
    "id": {
        "dan",
        "yang",
        "dengan",
        "untuk",
        "di",
        "ke",
        "dari",
        "kami",
        "anda",
        "pengalaman",
        "memiliki",
        "kemampuan",
        "persyaratan",
        "bekerja",
        "tahun",
    },
    "vi": {
        "và",
        "của",
        "với",
        "cho",
        "có",
        "các",
        "những",
        "được",
        "là",
        "kinh",
        "nghiệm",
        "yêu",
        "cầu",
        "làm",
        "việc",
    },
    "fil": {
        "ang",
        "ng",
        "mga",
        "sa",
        "na",
        "at",
        "para",
        "ay",
        "kami",
        "karanasan",
        "kailangan",
        "trabaho",
        "kasanayan",
        "naming",
        "ninyo",
    },
    "et": {
        "ja",
        "on",
        "ning",
        "ka",
        "et",
        "meie",
        "sinu",
        "töö",
        "otsime",
        "kogemus",
        "kogemust",
        "nõuded",
        "aastat",
        "oskus",
        "arendajat",
    },
}
