"""Words that say a message holds a secret, in prepza's 23 languages (secrets_check.py): with
one of them anywhere in a message, a long letter-and-digit value in it counts as a secret.
Latin-script words match at a word's start (key, keys, password…); the others anywhere."""

SECRET_WORDS = [
    # English
    "secret",
    "key",
    "api key",
    "token",
    "password",
    "passcode",
    "passwd",
    "credential",
    "bearer",
    "private key",
    "webhook secret",
    # Spanish, Portuguese, Italian, French
    "secreto",
    "clave",
    "contraseña",
    "credencial",
    "segredo",
    "chave",
    "senha",
    "segreto",
    "chiave",
    "credenziali",
    "clé",
    "cle",
    "mot de passe",
    "jeton",
    # German, Dutch, Polish, Turkish, Estonian, Indonesian, Vietnamese, Filipino
    "geheim",
    "schlüssel",
    "schluessel",
    "passwort",
    "kennwort",
    "zugangsdaten",
    "sleutel",
    "wachtwoord",
    "inloggegevens",
    "sekret",
    "klucz",
    "hasło",
    "haslo",
    "poświadczenia",
    "gizli",
    "anahtar",
    "şifre",
    "sifre",
    "parola",
    "saladus",
    "võti",
    "voti",
    "parool",
    "rahasia",
    "kunci",
    "kata sandi",
    "sandi",
    "khóa",
    "mật khẩu",
    "bí mật",
    "lihim",
    "susi",
    # Russian, Ukrainian
    "секрет",
    "ключ",
    "токен",
    "пароль",
    "учётные данные",
    "учетные данные",
    "облікові дані",
    # Arabic, Hebrew, Persian
    "سر",
    "مفتاح",
    "كلمة المرور",
    "كلمة السر",
    "סוד",
    "מפתח",
    "סיסמה",
    "סיסמא",
    "טוקן",
    "کلید",
    "رمز",
    "گذرواژه",
    "توکن",
    # Japanese, Chinese, Korean
    "シークレット",
    "キー",
    "パスワード",
    "トークン",
    "秘密鍵",
    "認証情報",
    "密钥",
    "秘钥",
    "密码",
    "令牌",
    "凭证",
    "시크릿",
    "키",
    "비밀번호",
    "토큰",
    "자격 증명",
    # Hindi, Thai
    "कुंजी",
    "पासवर्ड",
    "टोकन",
    "सीक्रेट",
    "गुप्त",
    "คีย์",
    "รหัสผ่าน",
    "โทเคน",
    "ความลับ",
]

# Words that say which form a secret belongs in, when the message names it.
ATS_WORDS = [
    "greenhouse",
    "workable",
    "teamtailor",
    "recruitee",
    "breezy",
    "ats",
    "integration",
    "интеграц",
    "інтеграц",
    "integración",
    "integração",
    "integrazione",
    "intégration",
    "integratie",
    "integracj",
    "entegrasyon",
    "integratsioon",
    "integrasi",
]
SLACK_WORDS = ["slack"]
API_WORDS = ["api", "webhook", "web hook", "pz_", "whsec_"]
