# More reads (see tools.py for the entries' keys): an interview's questions and their reports,
# the company's audit log, the user's email settings, templates to copy, an ATS job's stages,
# prepza's news and the user's own practice.

DETAIL_TOOLS = {
    "list_topic_questions": {
        "service": "companies",
        "method": "GET",
        "path": "/interviews/{interview_id}/topics/{topic_id}/questions",
        "params": ["interview_id", "topic_id"],
        "fields": ["id", "text", "options", "likes", "dislikes", "reports"],
        "max_items": 30,
    },
    "list_question_reports": {
        "service": "companies",
        "method": "GET",
        "path": "/interviews/{interview_id}/questions/{question_id}/reports",
        "params": ["interview_id", "question_id", "offset", "limit"],
        "fields": ["id", "reason", "comment", "created_at"],
    },
    "list_audit_events": {
        "service": "companies",
        "method": "GET",
        "path": "/companies/{company_id}/audit",
        "params": ["company_id", "offset", "limit"],
        "fields": ["user_id", "action", "target_id", "via", "created_at"],
    },
    "get_email_preferences": {
        "service": "library",
        "method": "GET",
        "path": "/me/email-preferences",
        "params": [],
    },
    "list_copyable_templates": {
        "service": "library",
        "method": "GET",
        "path": "/templates/copyable",
        "params": ["q", "level", "language", "offset", "limit"],
        "fields": ["id", "title", "level", "language", "topic_count"],
    },
    "list_ats_stages": {
        "service": "ats",
        "method": "GET",
        "path": "/{provider}/jobs/{job_id}/stages",
        "params": ["provider", "job_id", "company_id"],
        "fields": ["id", "name"],
    },
    "list_news": {
        "service": "library",
        "method": "GET",
        "path": "/news",
        "params": ["offset", "limit"],
        "fields": ["id", "title", "text", "published_on"],
        "max_items": 10,
    },
    "list_practice_rounds": {
        "service": "rounds",
        "method": "GET",
        "path": "/practice/{template_id}/rounds",
        "params": ["template_id"],
        "fields": ["round_id", "started_at", "finished", "progress", "grade"],
    },
    "get_practice_progress": {
        "service": "rounds",
        "method": "GET",
        "path": "/practice/{template_id}/progress",
        "params": ["template_id"],
        "fields": ["topic_id", "answered", "total"],
    },
}
