"""Column headers of a candidate list's name columns, in English and the 23 languages' usual
words, matched after lowercasing and turning "_", "-" and runs of spaces into one space."""

# A whole name in one column.
FULL_NAME_HEADERS = {
    "name",
    "full name",
    "fullname",
    "candidate",
    "candidate name",
    "applicant",
    "applicant name",
    "vollständiger name",
    "nom complet",
    "nom et prénom",
    "nombre completo",
    "nombre y apellidos",
    "nome completo",
    "nome e cognome",
    "имя и фамилия",
    "фио",
    "ім'я та прізвище",
    "піб",
    "imię i nazwisko",
    "volledige naam",
    "ad soyad",
    "adı soyadı",
    "isim",
    "الاسم",
    "الاسم الكامل",
    "نام و نام خانوادگی",
    "نام کامل",
    "שם",
    "שם מלא",
    "नाम",
    "पूरा नाम",
    "氏名",
    "名前",
    "이름",
    "성명",
    "姓名",
    "ชื่อ-นามสกุล",
    "ชื่อ นามสกุล",
    "họ tên",
    "họ và tên",
    "nama",
    "nama lengkap",
    "pangalan",
    "buong pangalan",
    "nimi",
    "täisnimi",
    "naam",
    "nom",
    "nombre",
    "nome",
    "имя",
}
FIRST_NAME_HEADERS = {
    "first name",
    "firstname",
    "given name",
    "forename",
    "vorname",
    "prénom",
    "nombre de pila",
    "nome proprio",
    "primeiro nome",
    "imię",
    "voornaam",
    "ad",
    "الاسم الأول",
    "نام کوچک",
    "שם פרטי",
    "पहला नाम",
    "名",
    "ชื่อจริง",
    "tên",
    "nama depan",
    "unang pangalan",
    "eesnimi",
    "ім'я",
}
# With a first-name column beside it, "name" or "nom" holds the surname (as in "Name, Vorname").
LAST_NAME_HEADERS = {
    "name",
    "nom",
    "last name",
    "lastname",
    "surname",
    "family name",
    "nachname",
    "familienname",
    "nom de famille",
    "apellido",
    "apellidos",
    "cognome",
    "sobrenome",
    "apelido",
    "фамилия",
    "прізвище",
    "nazwisko",
    "achternaam",
    "soyad",
    "soyadı",
    "اسم العائلة",
    "نام خانوادگی",
    "שם משפחה",
    "उपनाम",
    "姓",
    "성",
    "นามสกุล",
    "họ",
    "nama belakang",
    "apelyido",
    "perekonnanimi",
}
